// Generated by ts-to-zod
import { z } from 'zod'

export const calendarUnitFormatModeSchema = z.union([
	z.literal('Name'),
	z.literal('NameOneIndexed'),
	z.literal('Numeric'),
	z.literal('NumericOneIndexed'),
	z.literal('Hidden'),
])

export const calendarUnitNegativeFormatSchema = z.union([z.literal('MinusSign'), z.literal('AbsoluteValue')])

export const mentionedEntitySchema = z.union([
	z.literal('Actor'),
	z.literal('Event'),
	z.literal('Article'),
	z.literal('Tag'),
])

export const mindmapLinkDirectionSchema = z.union([
	z.literal('Normal'),
	z.literal('Reversed'),
	z.literal('TwoWay'),
])

export const worldAccessModeSchema = z.union([
	z.literal('Private'),
	z.literal('PublicRead'),
	z.literal('PublicEdit'),
])

export const worldCalendarTypeSchema = z.union([
	z.literal('COUNTUP'),
	z.literal('EARTH'),
	z.literal('PF2E'),
	z.literal('RIMWORLD'),
	z.literal('EXETHER'),
])

export const exportedUserDataSchema = z.object({
	version: z.literal(1),
	user: z.object({
		id: z.string(),
		calendars: z.array(
			z
				.object({
					units: z.array(
						z
							.object({
								children: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										position: z.number(),
										calendarId: z.string(),
										label: z.string().nullable(),
										shortLabel: z.string().nullable(),
										repeats: z.number(),
										parentUnitId: z.string(),
										childUnitId: z.string(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									position: z.number(),
									displayName: z.string().nullable(),
									displayNameShort: z.string().nullable(),
									displayNamePlural: z.string().nullable(),
									formatMode: calendarUnitFormatModeSchema,
									formatShorthand: z.string().nullable(),
									negativeFormat: calendarUnitNegativeFormatSchema,
									duration: z.bigint(),
									treeDepth: z.number(),
									calendarId: z.string(),
								}),
							),
					),
					seasons: z.array(
						z
							.object({
								intervals: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										calendarId: z.string(),
										leftIndex: z.number(),
										rightIndex: z.number(),
										seasonId: z.string(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									position: z.number(),
									formatShorthand: z.string().nullable(),
									calendarId: z.string(),
								}),
							),
					),
					presentations: z.array(
						z
							.object({
								units: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										name: z.string(),
										position: z.number(),
										calendarId: z.string(),
										formatString: z.string(),
										subdivision: z.number(),
										labeledIndices: z.array(z.number()),
										unitId: z.string(),
										presentationId: z.string(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									calendarId: z.string(),
									compression: z.number(),
									scaleFactor: z.number(),
									baselineUnitId: z.string().nullable(),
								}),
							),
					),
				})
				.and(
					z.object({
						id: z.string(),
						createdAt: z.date(),
						updatedAt: z.date(),
						name: z.string(),
						description: z.string(),
						worldId: z.string().nullable(),
						ownerId: z.string().nullable(),
						position: z.number(),
						originTime: z.bigint(),
						dateFormat: z.string().nullable(),
					}),
				),
		),
		worlds: z.array(
			z
				.object({
					calendars: z.array(
						z
							.object({
								units: z.array(
									z
										.object({
											children: z.array(
												z.object({
													id: z.string(),
													createdAt: z.date(),
													updatedAt: z.date(),
													position: z.number(),
													calendarId: z.string(),
													label: z.string().nullable(),
													shortLabel: z.string().nullable(),
													repeats: z.number(),
													parentUnitId: z.string(),
													childUnitId: z.string(),
												}),
											),
										})
										.and(
											z.object({
												id: z.string(),
												createdAt: z.date(),
												updatedAt: z.date(),
												name: z.string(),
												position: z.number(),
												displayName: z.string().nullable(),
												displayNameShort: z.string().nullable(),
												displayNamePlural: z.string().nullable(),
												formatMode: calendarUnitFormatModeSchema,
												formatShorthand: z.string().nullable(),
												negativeFormat: calendarUnitNegativeFormatSchema,
												duration: z.bigint(),
												treeDepth: z.number(),
												calendarId: z.string(),
											}),
										),
								),
								seasons: z.array(
									z
										.object({
											intervals: z.array(
												z.object({
													id: z.string(),
													createdAt: z.date(),
													updatedAt: z.date(),
													calendarId: z.string(),
													leftIndex: z.number(),
													rightIndex: z.number(),
													seasonId: z.string(),
												}),
											),
										})
										.and(
											z.object({
												id: z.string(),
												createdAt: z.date(),
												updatedAt: z.date(),
												name: z.string(),
												position: z.number(),
												formatShorthand: z.string().nullable(),
												calendarId: z.string(),
											}),
										),
								),
								presentations: z.array(
									z
										.object({
											units: z.array(
												z.object({
													id: z.string(),
													createdAt: z.date(),
													updatedAt: z.date(),
													name: z.string(),
													position: z.number(),
													calendarId: z.string(),
													formatString: z.string(),
													subdivision: z.number(),
													labeledIndices: z.array(z.number()),
													unitId: z.string(),
													presentationId: z.string(),
												}),
											),
										})
										.and(
											z.object({
												id: z.string(),
												createdAt: z.date(),
												updatedAt: z.date(),
												name: z.string(),
												calendarId: z.string(),
												compression: z.number(),
												scaleFactor: z.number(),
												baselineUnitId: z.string().nullable(),
											}),
										),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									description: z.string(),
									worldId: z.string().nullable(),
									ownerId: z.string().nullable(),
									position: z.number(),
									originTime: z.bigint(),
									dateFormat: z.string().nullable(),
								}),
							),
					),
					tags: z.array(
						z
							.object({
								mentions: z.array(
									z.object({
										sourceId: z.string(),
										targetId: z.string(),
										sourceType: mentionedEntitySchema,
										targetType: mentionedEntitySchema,
										sourceActorId: z.string().nullable(),
										sourceEventId: z.string().nullable(),
										sourceArticleId: z.string().nullable(),
										sourceTagId: z.string().nullable(),
										targetActorId: z.string().nullable(),
										targetEventId: z.string().nullable(),
										targetArticleId: z.string().nullable(),
										targetTagId: z.string().nullable(),
										pageId: z.string().nullable(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									description: z.string(),
									worldId: z.string(),
								}),
							),
					),
					savedColors: z.array(
						z.object({
							id: z.string(),
							createdAt: z.date(),
							updatedAt: z.date(),
							worldId: z.string(),
							label: z.string().nullable(),
							value: z.string(),
						}),
					),
					worldCommonIconSets: z.array(
						z.object({
							id: z.string(),
							worldId: z.string(),
							iconSet: z.string(),
						}),
					),
					worldEventTracks: z.array(
						z.object({
							id: z.string(),
							createdAt: z.date(),
							updatedAt: z.date(),
							name: z.string(),
							worldId: z.string(),
							position: z.number(),
							visible: z.boolean(),
						}),
					),
					actors: z.array(
						z
							.object({
								mentions: z.array(
									z.object({
										sourceId: z.string(),
										targetId: z.string(),
										sourceType: mentionedEntitySchema,
										targetType: mentionedEntitySchema,
										sourceActorId: z.string().nullable(),
										sourceEventId: z.string().nullable(),
										sourceArticleId: z.string().nullable(),
										sourceTagId: z.string().nullable(),
										targetActorId: z.string().nullable(),
										targetEventId: z.string().nullable(),
										targetArticleId: z.string().nullable(),
										targetTagId: z.string().nullable(),
										pageId: z.string().nullable(),
									}),
								),
								pages: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										name: z.string(),
										description: z.string(),
										descriptionRich: z.string(),
										parentActorId: z.string().nullable(),
										parentEventId: z.string().nullable(),
										parentArticleId: z.string().nullable(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									title: z.string(),
									icon: z.string(),
									color: z.string(),
									description: z.string(),
									descriptionRich: z.string(),
									worldId: z.string(),
								}),
							),
					),
					events: z.array(
						z
							.object({
								mentions: z.array(
									z.object({
										sourceId: z.string(),
										targetId: z.string(),
										sourceType: mentionedEntitySchema,
										targetType: mentionedEntitySchema,
										sourceActorId: z.string().nullable(),
										sourceEventId: z.string().nullable(),
										sourceArticleId: z.string().nullable(),
										sourceTagId: z.string().nullable(),
										targetActorId: z.string().nullable(),
										targetEventId: z.string().nullable(),
										targetArticleId: z.string().nullable(),
										targetTagId: z.string().nullable(),
										pageId: z.string().nullable(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									icon: z.string(),
									color: z.string(),
									description: z.string(),
									descriptionRich: z.string(),
									worldId: z.string(),
									timestamp: z.bigint(),
									revokedAt: z.bigint().nullable(),
									worldEventTrackId: z.string().nullable(),
								}),
							),
					),
					articles: z.array(
						z
							.object({
								mentions: z.array(
									z.object({
										sourceId: z.string(),
										targetId: z.string(),
										sourceType: mentionedEntitySchema,
										targetType: mentionedEntitySchema,
										sourceActorId: z.string().nullable(),
										sourceEventId: z.string().nullable(),
										sourceArticleId: z.string().nullable(),
										sourceTagId: z.string().nullable(),
										targetActorId: z.string().nullable(),
										targetEventId: z.string().nullable(),
										targetArticleId: z.string().nullable(),
										targetTagId: z.string().nullable(),
										pageId: z.string().nullable(),
									}),
								),
								pages: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										name: z.string(),
										description: z.string(),
										descriptionRich: z.string(),
										parentActorId: z.string().nullable(),
										parentEventId: z.string().nullable(),
										parentArticleId: z.string().nullable(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									name: z.string(),
									icon: z.string(),
									color: z.string(),
									worldId: z.string(),
									position: z.number(),
									contentRich: z.string(),
									parentId: z.string().nullable(),
								}),
							),
					),
					mindmapNodes: z.array(
						z
							.object({
								links: z.array(
									z.object({
										id: z.string(),
										createdAt: z.date(),
										updatedAt: z.date(),
										sourceNodeId: z.string(),
										targetNodeId: z.string(),
										direction: mindmapLinkDirectionSchema,
										content: z.string(),
									}),
								),
							})
							.and(
								z.object({
									id: z.string(),
									createdAt: z.date(),
									updatedAt: z.date(),
									worldId: z.string(),
									parentActorId: z.string().nullable(),
									positionX: z.number(),
									positionY: z.number(),
								}),
							),
					),
				})
				.and(
					z.object({
						id: z.string(),
						createdAt: z.date(),
						updatedAt: z.date(),
						name: z.string(),
						description: z.string(),
						ownerId: z.string(),
						calendar: worldCalendarTypeSchema.nullable(),
						timeOrigin: z.bigint(),
						accessMode: worldAccessModeSchema,
					}),
				),
		),
	}),
})
