FROM nginx:mainline

COPY default.prod.conf /etc/nginx/conf.d/default.conf
COPY scripts/init-certbot.sh /docker-entrypoint.d/99-init-certbot.sh
COPY scripts/install-certbot.sh .
RUN ./install-certbot.sh