/*
  Warnings:

  - A unique constraint covering the columns `[assetId,holderId,pageId]` on the table `AssetReference` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[id]` on the table `Mention` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[sourceId,targetId,pageId]` on the table `Mention` will be added. If there are existing duplicate values, this will fail.
  - The required column `id` was added to the `Mention` table with a prisma-level default value. This is not possible if the table is not empty. Please add this column as optional, then populate it before making it required.

*/
-- DropIndex
DROP INDEX "AssetReference_assetId_holderId_key";

-- DropIndex
DROP INDEX "Mention_sourceId_targetId_key";

-- AlterTable
-- Add the primary key, backfilling existing rows in place: add the column with a
-- DB-level default so every current row gets a UUID, then drop the default so the
-- column matches Prisma's app-level @default(uuid()) (ids generated by the client).
ALTER TABLE "Mention" ADD COLUMN "id" TEXT NOT NULL DEFAULT gen_random_uuid()::text;
ALTER TABLE "Mention" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Mention" ADD CONSTRAINT "Mention_pkey" PRIMARY KEY ("id");

-- CreateIndex
CREATE UNIQUE INDEX "AssetReference_assetId_holderId_pageId_key" ON "AssetReference"("assetId", "holderId", "pageId");

-- CreateIndex
CREATE UNIQUE INDEX "Mention_id_key" ON "Mention"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Mention_sourceId_targetId_pageId_key" ON "Mention"("sourceId", "targetId", "pageId");
