version: "3.1"
services:
    styx:
        build:
            context: ./
            dockerfile: ./app/styx-frontend/Dockerfile
        image: localhost:5000/styx
        working_dir: /app/styx
        environment:
            NODE_ENV: development
        depends_on:
            - rhea
        ports:
            - 8080:8080
        command: bash -c "yarn start"
        volumes:
            - ./app/styx-frontend/src:/app/styx/src:cached
            - ./app/styx-frontend/public:/app/styx/public:cached
            - ./app/shared/src:/app/shared/src:cached
        tty: true
        restart: on-failure
    rhea:
        build:
            context: ./
            dockerfile: ./app/rhea-backend/Dockerfile
        image: localhost:5000/rhea
        working_dir: /app/rhea
        environment:
            NODE_ENV: development
            DATABASE_URL: postgresql://docker:docker@rhea-postgres:5432/db?schema=public
        depends_on:
            - rhea-postgres
        ports:
            - 3000:3000
        command: yarn start
        volumes:
            - ./app/styx-frontend/public:/app/styx/public:cached
            - ./app/rhea-backend/src:/app/rhea/src:cached
            - ./app/shared/src:/app/shared/src:cached
        tty: true
        restart: on-failure
    rhea-postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: db
        ports:
            - 5432:5432
        volumes:
            - rhea-db:/var/lib/postgresql/data/:cached
        restart: on-failure
volumes:
    rhea-db:
