version: "3.1"
services:
    styx:
        build:
            context: ./
            dockerfile: ./app/styx-frontend/Dockerfile
        environment:
            NODE_ENV: development
        volumes:
            - ./app/styx-frontend/src:/app/styx/src:cached
            - ./app/styx-frontend/public:/app/styx/public:cached
        command: yarn start
        tty: true
        restart: on-failure
    rhea:
        build:
            context: ./
            dockerfile: ./app/rhea-backend/Dockerfile
        environment:
            NODE_ENV: development
            DATABASE_URL: postgresql://docker:docker@rhea-postgres:5432/db?schema=public
        volumes:
            - ./app/styx-frontend/public:/app/styx/public:cached
            - ./app/rhea-backend/src:/app/rhea/src:cached
        command: yarn start
        tty: true
        restart: on-failure
    rhea-postgres:
        image: postgres:11.5-alpine
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: db
        ports:
            - 5432:5432
        volumes:
            - rhea-db:/var/lib/postgresql/data/:cached
        restart: on-failure
volumes:
    rhea-db:
