
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import type * as Prisma from "./internal/prismaNamespace.js"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumAnnouncementTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.AnnouncementType | Prisma.EnumAnnouncementTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel> | $Enums.AnnouncementType
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumAnnouncementTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AnnouncementType | Prisma.EnumAnnouncementTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAnnouncementTypeWithAggregatesFilter<$PrismaModel> | $Enums.AnnouncementType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel>
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type EnumAssetTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetType | Prisma.EnumAssetTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel> | $Enums.AssetType
}

export type EnumAssetStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetStatus | Prisma.EnumAssetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel> | $Enums.AssetStatus
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumAssetTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetType | Prisma.EnumAssetTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetTypeWithAggregatesFilter<$PrismaModel> | $Enums.AssetType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel>
}

export type EnumAssetStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetStatus | Prisma.EnumAssetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetStatusWithAggregatesFilter<$PrismaModel> | $Enums.AssetStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel>
}

export type BigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type BigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type EnumCalendarUnitFormatModeFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitFormatMode | Prisma.EnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel> | $Enums.CalendarUnitFormatMode
}

export type EnumCalendarUnitNegativeFormatFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitNegativeFormat | Prisma.EnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel> | $Enums.CalendarUnitNegativeFormat
}

export type EnumCalendarUnitFormatModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitFormatMode | Prisma.EnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitFormatModeWithAggregatesFilter<$PrismaModel> | $Enums.CalendarUnitFormatMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel>
}

export type EnumCalendarUnitNegativeFormatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitNegativeFormat | Prisma.EnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitNegativeFormatWithAggregatesFilter<$PrismaModel> | $Enums.CalendarUnitNegativeFormat
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel>
}

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type EnumFlagValueFilter<$PrismaModel = never> = {
  equals?: $Enums.FlagValue | Prisma.EnumFlagValueFieldRefInput<$PrismaModel>
  in?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  notIn?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumFlagValueFilter<$PrismaModel> | $Enums.FlagValue
}

export type EnumFlagValueWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.FlagValue | Prisma.EnumFlagValueFieldRefInput<$PrismaModel>
  in?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  notIn?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumFlagValueWithAggregatesFilter<$PrismaModel> | $Enums.FlagValue
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumFlagValueFilter<$PrismaModel>
  _max?: Prisma.NestedEnumFlagValueFilter<$PrismaModel>
}

export type EnumMentionedEntityFilter<$PrismaModel = never> = {
  equals?: $Enums.MentionedEntity | Prisma.EnumMentionedEntityFieldRefInput<$PrismaModel>
  in?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  notIn?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel> | $Enums.MentionedEntity
}

export type EnumMentionedEntityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MentionedEntity | Prisma.EnumMentionedEntityFieldRefInput<$PrismaModel>
  in?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  notIn?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMentionedEntityWithAggregatesFilter<$PrismaModel> | $Enums.MentionedEntity
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel>
}

export type EnumUserLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.UserLevel | Prisma.EnumUserLevelFieldRefInput<$PrismaModel>
  in?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserLevelFilter<$PrismaModel> | $Enums.UserLevel
}

export type EnumUserLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserLevel | Prisma.EnumUserLevelFieldRefInput<$PrismaModel>
  in?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserLevelWithAggregatesFilter<$PrismaModel> | $Enums.UserLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserLevelFilter<$PrismaModel>
}

export type EnumCollaboratorAccessFilter<$PrismaModel = never> = {
  equals?: $Enums.CollaboratorAccess | Prisma.EnumCollaboratorAccessFieldRefInput<$PrismaModel>
  in?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  notIn?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel> | $Enums.CollaboratorAccess
}

export type EnumCollaboratorAccessWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CollaboratorAccess | Prisma.EnumCollaboratorAccessFieldRefInput<$PrismaModel>
  in?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  notIn?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCollaboratorAccessWithAggregatesFilter<$PrismaModel> | $Enums.CollaboratorAccess
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel>
}

export type EnumWorldCalendarTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldCalendarType | Prisma.EnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel> | $Enums.WorldCalendarType
}

export type EnumWorldAccessModeFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldAccessMode | Prisma.EnumWorldAccessModeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel> | $Enums.WorldAccessMode
}

export type EnumWorldCalendarTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldCalendarType | Prisma.EnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldCalendarTypeWithAggregatesFilter<$PrismaModel> | $Enums.WorldCalendarType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel>
}

export type EnumWorldAccessModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldAccessMode | Prisma.EnumWorldAccessModeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldAccessModeWithAggregatesFilter<$PrismaModel> | $Enums.WorldAccessMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel>
}

export type BigIntNullableFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableFilter<$PrismaModel> | bigint | number | null
}

export type BigIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableWithAggregatesFilter<$PrismaModel> | bigint | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumAnnouncementTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.AnnouncementType | Prisma.EnumAnnouncementTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel> | $Enums.AnnouncementType
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumAnnouncementTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AnnouncementType | Prisma.EnumAnnouncementTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AnnouncementType[] | Prisma.ListEnumAnnouncementTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAnnouncementTypeWithAggregatesFilter<$PrismaModel> | $Enums.AnnouncementType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAnnouncementTypeFilter<$PrismaModel>
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumAssetTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetType | Prisma.EnumAssetTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel> | $Enums.AssetType
}

export type NestedEnumAssetStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetStatus | Prisma.EnumAssetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel> | $Enums.AssetStatus
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumAssetTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetType | Prisma.EnumAssetTypeFieldRefInput<$PrismaModel>
  in?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetType[] | Prisma.ListEnumAssetTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetTypeWithAggregatesFilter<$PrismaModel> | $Enums.AssetType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssetTypeFilter<$PrismaModel>
}

export type NestedEnumAssetStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.AssetStatus | Prisma.EnumAssetStatusFieldRefInput<$PrismaModel>
  in?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.AssetStatus[] | Prisma.ListEnumAssetStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumAssetStatusWithAggregatesFilter<$PrismaModel> | $Enums.AssetStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumAssetStatusFilter<$PrismaModel>
}

export type NestedBigIntFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntFilter<$PrismaModel> | bigint | number
}

export type NestedBigIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel>
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntWithAggregatesFilter<$PrismaModel> | bigint | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntFilter<$PrismaModel>
}

export type NestedEnumCalendarUnitFormatModeFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitFormatMode | Prisma.EnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel> | $Enums.CalendarUnitFormatMode
}

export type NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitNegativeFormat | Prisma.EnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel> | $Enums.CalendarUnitNegativeFormat
}

export type NestedEnumCalendarUnitFormatModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitFormatMode | Prisma.EnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitFormatMode[] | Prisma.ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitFormatModeWithAggregatesFilter<$PrismaModel> | $Enums.CalendarUnitFormatMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCalendarUnitFormatModeFilter<$PrismaModel>
}

export type NestedEnumCalendarUnitNegativeFormatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CalendarUnitNegativeFormat | Prisma.EnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  in?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  notIn?: $Enums.CalendarUnitNegativeFormat[] | Prisma.ListEnumCalendarUnitNegativeFormatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCalendarUnitNegativeFormatWithAggregatesFilter<$PrismaModel> | $Enums.CalendarUnitNegativeFormat
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCalendarUnitNegativeFormatFilter<$PrismaModel>
}

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type NestedEnumFlagValueFilter<$PrismaModel = never> = {
  equals?: $Enums.FlagValue | Prisma.EnumFlagValueFieldRefInput<$PrismaModel>
  in?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  notIn?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumFlagValueFilter<$PrismaModel> | $Enums.FlagValue
}

export type NestedEnumFlagValueWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.FlagValue | Prisma.EnumFlagValueFieldRefInput<$PrismaModel>
  in?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  notIn?: $Enums.FlagValue[] | Prisma.ListEnumFlagValueFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumFlagValueWithAggregatesFilter<$PrismaModel> | $Enums.FlagValue
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumFlagValueFilter<$PrismaModel>
  _max?: Prisma.NestedEnumFlagValueFilter<$PrismaModel>
}

export type NestedEnumMentionedEntityFilter<$PrismaModel = never> = {
  equals?: $Enums.MentionedEntity | Prisma.EnumMentionedEntityFieldRefInput<$PrismaModel>
  in?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  notIn?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel> | $Enums.MentionedEntity
}

export type NestedEnumMentionedEntityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MentionedEntity | Prisma.EnumMentionedEntityFieldRefInput<$PrismaModel>
  in?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  notIn?: $Enums.MentionedEntity[] | Prisma.ListEnumMentionedEntityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMentionedEntityWithAggregatesFilter<$PrismaModel> | $Enums.MentionedEntity
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMentionedEntityFilter<$PrismaModel>
}

export type NestedEnumUserLevelFilter<$PrismaModel = never> = {
  equals?: $Enums.UserLevel | Prisma.EnumUserLevelFieldRefInput<$PrismaModel>
  in?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserLevelFilter<$PrismaModel> | $Enums.UserLevel
}

export type NestedEnumUserLevelWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserLevel | Prisma.EnumUserLevelFieldRefInput<$PrismaModel>
  in?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserLevel[] | Prisma.ListEnumUserLevelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserLevelWithAggregatesFilter<$PrismaModel> | $Enums.UserLevel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserLevelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserLevelFilter<$PrismaModel>
}

export type NestedEnumCollaboratorAccessFilter<$PrismaModel = never> = {
  equals?: $Enums.CollaboratorAccess | Prisma.EnumCollaboratorAccessFieldRefInput<$PrismaModel>
  in?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  notIn?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel> | $Enums.CollaboratorAccess
}

export type NestedEnumCollaboratorAccessWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CollaboratorAccess | Prisma.EnumCollaboratorAccessFieldRefInput<$PrismaModel>
  in?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  notIn?: $Enums.CollaboratorAccess[] | Prisma.ListEnumCollaboratorAccessFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCollaboratorAccessWithAggregatesFilter<$PrismaModel> | $Enums.CollaboratorAccess
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCollaboratorAccessFilter<$PrismaModel>
}

export type NestedEnumWorldCalendarTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldCalendarType | Prisma.EnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel> | $Enums.WorldCalendarType
}

export type NestedEnumWorldAccessModeFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldAccessMode | Prisma.EnumWorldAccessModeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel> | $Enums.WorldAccessMode
}

export type NestedEnumWorldCalendarTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldCalendarType | Prisma.EnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldCalendarType[] | Prisma.ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldCalendarTypeWithAggregatesFilter<$PrismaModel> | $Enums.WorldCalendarType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorldCalendarTypeFilter<$PrismaModel>
}

export type NestedEnumWorldAccessModeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorldAccessMode | Prisma.EnumWorldAccessModeFieldRefInput<$PrismaModel>
  in?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorldAccessMode[] | Prisma.ListEnumWorldAccessModeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorldAccessModeWithAggregatesFilter<$PrismaModel> | $Enums.WorldAccessMode
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorldAccessModeFilter<$PrismaModel>
}

export type NestedBigIntNullableFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableFilter<$PrismaModel> | bigint | number | null
}

export type NestedBigIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel> | null
  in?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  notIn?: bigint[] | number[] | Prisma.ListBigIntFieldRefInput<$PrismaModel> | null
  lt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  lte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gt?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  gte?: bigint | number | Prisma.BigIntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBigIntNullableWithAggregatesFilter<$PrismaModel> | bigint | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBigIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}


