
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AnnouncementType = {
  Info: 'Info',
  Welcome: 'Welcome',
  WorldShared: 'WorldShared'
} as const

export type AnnouncementType = (typeof AnnouncementType)[keyof typeof AnnouncementType]


export const AssetType = {
  ImageConversion: 'Image',
  Avatar: 'Avatar'
} as const

export type AssetType = (typeof AssetType)[keyof typeof AssetType]


export const AssetStatus = {
  Pending: 'Pending',
  Finalized: 'Finalized',
  Failed: 'Failed'
} as const

export type AssetStatus = (typeof AssetStatus)[keyof typeof AssetStatus]


export const FlagValue = {
  DatabaseSeeded: 'DatabaseSeeded',
  FirstUserLoggedIn: 'FirstUserLoggedIn'
} as const

export type FlagValue = (typeof FlagValue)[keyof typeof FlagValue]


export const MentionedEntity = {
  Actor: 'Actor',
  Event: 'Event',
  Article: 'Article',
  Tag: 'Tag'
} as const

export type MentionedEntity = (typeof MentionedEntity)[keyof typeof MentionedEntity]


export const UserLevel = {
  Free: 'Free',
  Premium: 'Premium',
  Admin: 'Admin'
} as const

export type UserLevel = (typeof UserLevel)[keyof typeof UserLevel]


export const CollaboratorAccess = {
  ReadOnly: 'ReadOnly',
  Editing: 'Editing'
} as const

export type CollaboratorAccess = (typeof CollaboratorAccess)[keyof typeof CollaboratorAccess]


export const WorldCalendarType = {
  COUNTUP: 'COUNTUP',
  EARTH: 'EARTH',
  PF2E: 'PF2E',
  RIMWORLD: 'RIMWORLD',
  EXETHER: 'EXETHER'
} as const

export type WorldCalendarType = (typeof WorldCalendarType)[keyof typeof WorldCalendarType]


export const WorldAccessMode = {
  Private: 'Private',
  PublicRead: 'PublicRead',
  PublicEdit: 'PublicEdit'
} as const

export type WorldAccessMode = (typeof WorldAccessMode)[keyof typeof WorldAccessMode]
