services:
  playwright:
    build: .
    volumes:
      - .:/app  # Mount the current directory into the container for live changes
    user: "${DOCKER_UID}:${DOCKER_GID}"
    environment:
      - TARGET_ENV
    command: npx playwright test