# Build stage
FROM node:25-alpine AS builder

WORKDIR /app/thetis

COPY ./app/thetis-landing/package.json ./app/thetis-landing/package-lock.json /app/thetis/
RUN npm ci

COPY ./app/thetis-landing /app/thetis
RUN npm run build

# Production stage - use nginx to serve static files
FROM nginx:alpine

COPY --from=builder /app/thetis/dist /usr/share/nginx/html
COPY ./app/thetis-landing/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8081
