# Build stage
FROM node:24-alpine AS builder

WORKDIR /app/thetis

COPY ./app/thetis-landing/package.json ./app/thetis-landing/yarn.lock /app/thetis/
RUN yarn install --frozen-lockfile

COPY ./app/thetis-landing /app/thetis
RUN yarn build

# Production stage - use nginx to serve static files
FROM nginx:alpine

COPY --from=builder /app/thetis/dist /usr/share/nginx/html
COPY ./app/thetis-landing/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8081
