FROM node:24-alpine

ARG VERSION=dev
ENV VERSION=${VERSION}

WORKDIR /app/styx

ADD ./app/styx-frontend /app/styx
ADD ./app/ts-shared /app/ts-shared
COPY .prettierrc.js /app/styx
RUN yarn && yarn build:ci && yarn prune-build-modules
