
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CalendarSeason` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CalendarSeason
 * *
 *  * Seasons
 */
export type CalendarSeasonModel = runtime.Types.Result.DefaultSelection<Prisma.$CalendarSeasonPayload>

export type AggregateCalendarSeason = {
  _count: CalendarSeasonCountAggregateOutputType | null
  _avg: CalendarSeasonAvgAggregateOutputType | null
  _sum: CalendarSeasonSumAggregateOutputType | null
  _min: CalendarSeasonMinAggregateOutputType | null
  _max: CalendarSeasonMaxAggregateOutputType | null
}

export type CalendarSeasonAvgAggregateOutputType = {
  position: number | null
}

export type CalendarSeasonSumAggregateOutputType = {
  position: number | null
}

export type CalendarSeasonMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  position: number | null
  name: string | null
  formatShorthand: string | null
  calendarId: string | null
}

export type CalendarSeasonMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  position: number | null
  name: string | null
  formatShorthand: string | null
  calendarId: string | null
}

export type CalendarSeasonCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  position: number
  name: number
  formatShorthand: number
  calendarId: number
  _all: number
}


export type CalendarSeasonAvgAggregateInputType = {
  position?: true
}

export type CalendarSeasonSumAggregateInputType = {
  position?: true
}

export type CalendarSeasonMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  position?: true
  name?: true
  formatShorthand?: true
  calendarId?: true
}

export type CalendarSeasonMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  position?: true
  name?: true
  formatShorthand?: true
  calendarId?: true
}

export type CalendarSeasonCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  position?: true
  name?: true
  formatShorthand?: true
  calendarId?: true
  _all?: true
}

export type CalendarSeasonAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CalendarSeason to aggregate.
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarSeasons to fetch.
   */
  orderBy?: Prisma.CalendarSeasonOrderByWithRelationInput | Prisma.CalendarSeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CalendarSeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarSeasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarSeasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CalendarSeasons
  **/
  _count?: true | CalendarSeasonCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CalendarSeasonAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CalendarSeasonSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CalendarSeasonMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CalendarSeasonMaxAggregateInputType
}

export type GetCalendarSeasonAggregateType<T extends CalendarSeasonAggregateArgs> = {
      [P in keyof T & keyof AggregateCalendarSeason]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCalendarSeason[P]>
    : Prisma.GetScalarType<T[P], AggregateCalendarSeason[P]>
}




export type CalendarSeasonGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalendarSeasonWhereInput
  orderBy?: Prisma.CalendarSeasonOrderByWithAggregationInput | Prisma.CalendarSeasonOrderByWithAggregationInput[]
  by: Prisma.CalendarSeasonScalarFieldEnum[] | Prisma.CalendarSeasonScalarFieldEnum
  having?: Prisma.CalendarSeasonScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CalendarSeasonCountAggregateInputType | true
  _avg?: CalendarSeasonAvgAggregateInputType
  _sum?: CalendarSeasonSumAggregateInputType
  _min?: CalendarSeasonMinAggregateInputType
  _max?: CalendarSeasonMaxAggregateInputType
}

export type CalendarSeasonGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  position: number
  name: string
  formatShorthand: string | null
  calendarId: string
  _count: CalendarSeasonCountAggregateOutputType | null
  _avg: CalendarSeasonAvgAggregateOutputType | null
  _sum: CalendarSeasonSumAggregateOutputType | null
  _min: CalendarSeasonMinAggregateOutputType | null
  _max: CalendarSeasonMaxAggregateOutputType | null
}

type GetCalendarSeasonGroupByPayload<T extends CalendarSeasonGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CalendarSeasonGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CalendarSeasonGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CalendarSeasonGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CalendarSeasonGroupByOutputType[P]>
      }
    >
  >



export type CalendarSeasonWhereInput = {
  AND?: Prisma.CalendarSeasonWhereInput | Prisma.CalendarSeasonWhereInput[]
  OR?: Prisma.CalendarSeasonWhereInput[]
  NOT?: Prisma.CalendarSeasonWhereInput | Prisma.CalendarSeasonWhereInput[]
  id?: Prisma.StringFilter<"CalendarSeason"> | string
  createdAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  position?: Prisma.IntFilter<"CalendarSeason"> | number
  name?: Prisma.StringFilter<"CalendarSeason"> | string
  formatShorthand?: Prisma.StringNullableFilter<"CalendarSeason"> | string | null
  calendarId?: Prisma.StringFilter<"CalendarSeason"> | string
  intervals?: Prisma.CalendarSeasonIntervalListRelationFilter
  calendar?: Prisma.XOR<Prisma.CalendarScalarRelationFilter, Prisma.CalendarWhereInput>
}

export type CalendarSeasonOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  position?: Prisma.SortOrder
  name?: Prisma.SortOrder
  formatShorthand?: Prisma.SortOrderInput | Prisma.SortOrder
  calendarId?: Prisma.SortOrder
  intervals?: Prisma.CalendarSeasonIntervalOrderByRelationAggregateInput
  calendar?: Prisma.CalendarOrderByWithRelationInput
}

export type CalendarSeasonWhereUniqueInput = Prisma.AtLeast<{
  calendarId_id?: Prisma.CalendarSeasonCalendarIdIdCompoundUniqueInput
  AND?: Prisma.CalendarSeasonWhereInput | Prisma.CalendarSeasonWhereInput[]
  OR?: Prisma.CalendarSeasonWhereInput[]
  NOT?: Prisma.CalendarSeasonWhereInput | Prisma.CalendarSeasonWhereInput[]
  id?: Prisma.StringFilter<"CalendarSeason"> | string
  createdAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  position?: Prisma.IntFilter<"CalendarSeason"> | number
  name?: Prisma.StringFilter<"CalendarSeason"> | string
  formatShorthand?: Prisma.StringNullableFilter<"CalendarSeason"> | string | null
  calendarId?: Prisma.StringFilter<"CalendarSeason"> | string
  intervals?: Prisma.CalendarSeasonIntervalListRelationFilter
  calendar?: Prisma.XOR<Prisma.CalendarScalarRelationFilter, Prisma.CalendarWhereInput>
}, "calendarId_id">

export type CalendarSeasonOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  position?: Prisma.SortOrder
  name?: Prisma.SortOrder
  formatShorthand?: Prisma.SortOrderInput | Prisma.SortOrder
  calendarId?: Prisma.SortOrder
  _count?: Prisma.CalendarSeasonCountOrderByAggregateInput
  _avg?: Prisma.CalendarSeasonAvgOrderByAggregateInput
  _max?: Prisma.CalendarSeasonMaxOrderByAggregateInput
  _min?: Prisma.CalendarSeasonMinOrderByAggregateInput
  _sum?: Prisma.CalendarSeasonSumOrderByAggregateInput
}

export type CalendarSeasonScalarWhereWithAggregatesInput = {
  AND?: Prisma.CalendarSeasonScalarWhereWithAggregatesInput | Prisma.CalendarSeasonScalarWhereWithAggregatesInput[]
  OR?: Prisma.CalendarSeasonScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CalendarSeasonScalarWhereWithAggregatesInput | Prisma.CalendarSeasonScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CalendarSeason"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CalendarSeason"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CalendarSeason"> | Date | string
  position?: Prisma.IntWithAggregatesFilter<"CalendarSeason"> | number
  name?: Prisma.StringWithAggregatesFilter<"CalendarSeason"> | string
  formatShorthand?: Prisma.StringNullableWithAggregatesFilter<"CalendarSeason"> | string | null
  calendarId?: Prisma.StringWithAggregatesFilter<"CalendarSeason"> | string
}

export type CalendarSeasonCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  intervals?: Prisma.CalendarSeasonIntervalCreateNestedManyWithoutSeasonInput
  calendar: Prisma.CalendarCreateNestedOneWithoutSeasonsInput
}

export type CalendarSeasonUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  calendarId: string
  intervals?: Prisma.CalendarSeasonIntervalUncheckedCreateNestedManyWithoutSeasonInput
}

export type CalendarSeasonUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervals?: Prisma.CalendarSeasonIntervalUpdateManyWithoutSeasonNestedInput
  calendar?: Prisma.CalendarUpdateOneRequiredWithoutSeasonsNestedInput
}

export type CalendarSeasonUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calendarId?: Prisma.StringFieldUpdateOperationsInput | string
  intervals?: Prisma.CalendarSeasonIntervalUncheckedUpdateManyWithoutSeasonNestedInput
}

export type CalendarSeasonCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  calendarId: string
}

export type CalendarSeasonUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CalendarSeasonUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calendarId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CalendarSeasonListRelationFilter = {
  every?: Prisma.CalendarSeasonWhereInput
  some?: Prisma.CalendarSeasonWhereInput
  none?: Prisma.CalendarSeasonWhereInput
}

export type CalendarSeasonOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CalendarSeasonCalendarIdIdCompoundUniqueInput = {
  calendarId: string
  id: string
}

export type CalendarSeasonCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  position?: Prisma.SortOrder
  name?: Prisma.SortOrder
  formatShorthand?: Prisma.SortOrder
  calendarId?: Prisma.SortOrder
}

export type CalendarSeasonAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type CalendarSeasonMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  position?: Prisma.SortOrder
  name?: Prisma.SortOrder
  formatShorthand?: Prisma.SortOrder
  calendarId?: Prisma.SortOrder
}

export type CalendarSeasonMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  position?: Prisma.SortOrder
  name?: Prisma.SortOrder
  formatShorthand?: Prisma.SortOrder
  calendarId?: Prisma.SortOrder
}

export type CalendarSeasonSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type CalendarSeasonScalarRelationFilter = {
  is?: Prisma.CalendarSeasonWhereInput
  isNot?: Prisma.CalendarSeasonWhereInput
}

export type CalendarSeasonCreateNestedManyWithoutCalendarInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput> | Prisma.CalendarSeasonCreateWithoutCalendarInput[] | Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput[]
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput | Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput[]
  createMany?: Prisma.CalendarSeasonCreateManyCalendarInputEnvelope
  connect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
}

export type CalendarSeasonUncheckedCreateNestedManyWithoutCalendarInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput> | Prisma.CalendarSeasonCreateWithoutCalendarInput[] | Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput[]
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput | Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput[]
  createMany?: Prisma.CalendarSeasonCreateManyCalendarInputEnvelope
  connect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
}

export type CalendarSeasonUpdateManyWithoutCalendarNestedInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput> | Prisma.CalendarSeasonCreateWithoutCalendarInput[] | Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput[]
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput | Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput[]
  upsert?: Prisma.CalendarSeasonUpsertWithWhereUniqueWithoutCalendarInput | Prisma.CalendarSeasonUpsertWithWhereUniqueWithoutCalendarInput[]
  createMany?: Prisma.CalendarSeasonCreateManyCalendarInputEnvelope
  set?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  disconnect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  delete?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  connect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  update?: Prisma.CalendarSeasonUpdateWithWhereUniqueWithoutCalendarInput | Prisma.CalendarSeasonUpdateWithWhereUniqueWithoutCalendarInput[]
  updateMany?: Prisma.CalendarSeasonUpdateManyWithWhereWithoutCalendarInput | Prisma.CalendarSeasonUpdateManyWithWhereWithoutCalendarInput[]
  deleteMany?: Prisma.CalendarSeasonScalarWhereInput | Prisma.CalendarSeasonScalarWhereInput[]
}

export type CalendarSeasonUncheckedUpdateManyWithoutCalendarNestedInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput> | Prisma.CalendarSeasonCreateWithoutCalendarInput[] | Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput[]
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput | Prisma.CalendarSeasonCreateOrConnectWithoutCalendarInput[]
  upsert?: Prisma.CalendarSeasonUpsertWithWhereUniqueWithoutCalendarInput | Prisma.CalendarSeasonUpsertWithWhereUniqueWithoutCalendarInput[]
  createMany?: Prisma.CalendarSeasonCreateManyCalendarInputEnvelope
  set?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  disconnect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  delete?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  connect?: Prisma.CalendarSeasonWhereUniqueInput | Prisma.CalendarSeasonWhereUniqueInput[]
  update?: Prisma.CalendarSeasonUpdateWithWhereUniqueWithoutCalendarInput | Prisma.CalendarSeasonUpdateWithWhereUniqueWithoutCalendarInput[]
  updateMany?: Prisma.CalendarSeasonUpdateManyWithWhereWithoutCalendarInput | Prisma.CalendarSeasonUpdateManyWithWhereWithoutCalendarInput[]
  deleteMany?: Prisma.CalendarSeasonScalarWhereInput | Prisma.CalendarSeasonScalarWhereInput[]
}

export type CalendarSeasonCreateNestedOneWithoutIntervalsInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedCreateWithoutIntervalsInput>
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutIntervalsInput
  connect?: Prisma.CalendarSeasonWhereUniqueInput
}

export type CalendarSeasonUpdateOneRequiredWithoutIntervalsNestedInput = {
  create?: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedCreateWithoutIntervalsInput>
  connectOrCreate?: Prisma.CalendarSeasonCreateOrConnectWithoutIntervalsInput
  upsert?: Prisma.CalendarSeasonUpsertWithoutIntervalsInput
  connect?: Prisma.CalendarSeasonWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CalendarSeasonUpdateToOneWithWhereWithoutIntervalsInput, Prisma.CalendarSeasonUpdateWithoutIntervalsInput>, Prisma.CalendarSeasonUncheckedUpdateWithoutIntervalsInput>
}

export type CalendarSeasonCreateWithoutCalendarInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  intervals?: Prisma.CalendarSeasonIntervalCreateNestedManyWithoutSeasonInput
}

export type CalendarSeasonUncheckedCreateWithoutCalendarInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  intervals?: Prisma.CalendarSeasonIntervalUncheckedCreateNestedManyWithoutSeasonInput
}

export type CalendarSeasonCreateOrConnectWithoutCalendarInput = {
  where: Prisma.CalendarSeasonWhereUniqueInput
  create: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput>
}

export type CalendarSeasonCreateManyCalendarInputEnvelope = {
  data: Prisma.CalendarSeasonCreateManyCalendarInput | Prisma.CalendarSeasonCreateManyCalendarInput[]
  skipDuplicates?: boolean
}

export type CalendarSeasonUpsertWithWhereUniqueWithoutCalendarInput = {
  where: Prisma.CalendarSeasonWhereUniqueInput
  update: Prisma.XOR<Prisma.CalendarSeasonUpdateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedUpdateWithoutCalendarInput>
  create: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedCreateWithoutCalendarInput>
}

export type CalendarSeasonUpdateWithWhereUniqueWithoutCalendarInput = {
  where: Prisma.CalendarSeasonWhereUniqueInput
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateWithoutCalendarInput, Prisma.CalendarSeasonUncheckedUpdateWithoutCalendarInput>
}

export type CalendarSeasonUpdateManyWithWhereWithoutCalendarInput = {
  where: Prisma.CalendarSeasonScalarWhereInput
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateManyMutationInput, Prisma.CalendarSeasonUncheckedUpdateManyWithoutCalendarInput>
}

export type CalendarSeasonScalarWhereInput = {
  AND?: Prisma.CalendarSeasonScalarWhereInput | Prisma.CalendarSeasonScalarWhereInput[]
  OR?: Prisma.CalendarSeasonScalarWhereInput[]
  NOT?: Prisma.CalendarSeasonScalarWhereInput | Prisma.CalendarSeasonScalarWhereInput[]
  id?: Prisma.StringFilter<"CalendarSeason"> | string
  createdAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CalendarSeason"> | Date | string
  position?: Prisma.IntFilter<"CalendarSeason"> | number
  name?: Prisma.StringFilter<"CalendarSeason"> | string
  formatShorthand?: Prisma.StringNullableFilter<"CalendarSeason"> | string | null
  calendarId?: Prisma.StringFilter<"CalendarSeason"> | string
}

export type CalendarSeasonCreateWithoutIntervalsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  calendar: Prisma.CalendarCreateNestedOneWithoutSeasonsInput
}

export type CalendarSeasonUncheckedCreateWithoutIntervalsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
  calendarId: string
}

export type CalendarSeasonCreateOrConnectWithoutIntervalsInput = {
  where: Prisma.CalendarSeasonWhereUniqueInput
  create: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedCreateWithoutIntervalsInput>
}

export type CalendarSeasonUpsertWithoutIntervalsInput = {
  update: Prisma.XOR<Prisma.CalendarSeasonUpdateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedUpdateWithoutIntervalsInput>
  create: Prisma.XOR<Prisma.CalendarSeasonCreateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedCreateWithoutIntervalsInput>
  where?: Prisma.CalendarSeasonWhereInput
}

export type CalendarSeasonUpdateToOneWithWhereWithoutIntervalsInput = {
  where?: Prisma.CalendarSeasonWhereInput
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateWithoutIntervalsInput, Prisma.CalendarSeasonUncheckedUpdateWithoutIntervalsInput>
}

export type CalendarSeasonUpdateWithoutIntervalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calendar?: Prisma.CalendarUpdateOneRequiredWithoutSeasonsNestedInput
}

export type CalendarSeasonUncheckedUpdateWithoutIntervalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calendarId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CalendarSeasonCreateManyCalendarInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  position: number
  name: string
  formatShorthand?: string | null
}

export type CalendarSeasonUpdateWithoutCalendarInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervals?: Prisma.CalendarSeasonIntervalUpdateManyWithoutSeasonNestedInput
}

export type CalendarSeasonUncheckedUpdateWithoutCalendarInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  intervals?: Prisma.CalendarSeasonIntervalUncheckedUpdateManyWithoutSeasonNestedInput
}

export type CalendarSeasonUncheckedUpdateManyWithoutCalendarInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  formatShorthand?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type CalendarSeasonCountOutputType
 */

export type CalendarSeasonCountOutputType = {
  intervals: number
}

export type CalendarSeasonCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  intervals?: boolean | CalendarSeasonCountOutputTypeCountIntervalsArgs
}

/**
 * CalendarSeasonCountOutputType without action
 */
export type CalendarSeasonCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeasonCountOutputType
   */
  select?: Prisma.CalendarSeasonCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CalendarSeasonCountOutputType without action
 */
export type CalendarSeasonCountOutputTypeCountIntervalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CalendarSeasonIntervalWhereInput
}


export type CalendarSeasonSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  position?: boolean
  name?: boolean
  formatShorthand?: boolean
  calendarId?: boolean
  intervals?: boolean | Prisma.CalendarSeason$intervalsArgs<ExtArgs>
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.CalendarSeasonCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calendarSeason"]>

export type CalendarSeasonSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  position?: boolean
  name?: boolean
  formatShorthand?: boolean
  calendarId?: boolean
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calendarSeason"]>

export type CalendarSeasonSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  position?: boolean
  name?: boolean
  formatShorthand?: boolean
  calendarId?: boolean
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
}, ExtArgs["result"]["calendarSeason"]>

export type CalendarSeasonSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  position?: boolean
  name?: boolean
  formatShorthand?: boolean
  calendarId?: boolean
}

export type CalendarSeasonOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "position" | "name" | "formatShorthand" | "calendarId", ExtArgs["result"]["calendarSeason"]>
export type CalendarSeasonInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  intervals?: boolean | Prisma.CalendarSeason$intervalsArgs<ExtArgs>
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.CalendarSeasonCountOutputTypeDefaultArgs<ExtArgs>
}
export type CalendarSeasonIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
}
export type CalendarSeasonIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  calendar?: boolean | Prisma.CalendarDefaultArgs<ExtArgs>
}

export type $CalendarSeasonPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CalendarSeason"
  objects: {
    intervals: Prisma.$CalendarSeasonIntervalPayload<ExtArgs>[]
    calendar: Prisma.$CalendarPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    position: number
    name: string
    formatShorthand: string | null
    calendarId: string
  }, ExtArgs["result"]["calendarSeason"]>
  composites: {}
}

export type CalendarSeasonGetPayload<S extends boolean | null | undefined | CalendarSeasonDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload, S>

export type CalendarSeasonCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CalendarSeasonFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CalendarSeasonCountAggregateInputType | true
  }

export interface CalendarSeasonDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CalendarSeason'], meta: { name: 'CalendarSeason' } }
  /**
   * Find zero or one CalendarSeason that matches the filter.
   * @param {CalendarSeasonFindUniqueArgs} args - Arguments to find a CalendarSeason
   * @example
   * // Get one CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CalendarSeasonFindUniqueArgs>(args: Prisma.SelectSubset<T, CalendarSeasonFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CalendarSeason that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CalendarSeasonFindUniqueOrThrowArgs} args - Arguments to find a CalendarSeason
   * @example
   * // Get one CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CalendarSeasonFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CalendarSeasonFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CalendarSeason that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonFindFirstArgs} args - Arguments to find a CalendarSeason
   * @example
   * // Get one CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CalendarSeasonFindFirstArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonFindFirstArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CalendarSeason that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonFindFirstOrThrowArgs} args - Arguments to find a CalendarSeason
   * @example
   * // Get one CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CalendarSeasonFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CalendarSeasons that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CalendarSeasons
   * const calendarSeasons = await prisma.calendarSeason.findMany()
   * 
   * // Get first 10 CalendarSeasons
   * const calendarSeasons = await prisma.calendarSeason.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const calendarSeasonWithIdOnly = await prisma.calendarSeason.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CalendarSeasonFindManyArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CalendarSeason.
   * @param {CalendarSeasonCreateArgs} args - Arguments to create a CalendarSeason.
   * @example
   * // Create one CalendarSeason
   * const CalendarSeason = await prisma.calendarSeason.create({
   *   data: {
   *     // ... data to create a CalendarSeason
   *   }
   * })
   * 
   */
  create<T extends CalendarSeasonCreateArgs>(args: Prisma.SelectSubset<T, CalendarSeasonCreateArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CalendarSeasons.
   * @param {CalendarSeasonCreateManyArgs} args - Arguments to create many CalendarSeasons.
   * @example
   * // Create many CalendarSeasons
   * const calendarSeason = await prisma.calendarSeason.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CalendarSeasonCreateManyArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CalendarSeasons and returns the data saved in the database.
   * @param {CalendarSeasonCreateManyAndReturnArgs} args - Arguments to create many CalendarSeasons.
   * @example
   * // Create many CalendarSeasons
   * const calendarSeason = await prisma.calendarSeason.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CalendarSeasons and only return the `id`
   * const calendarSeasonWithIdOnly = await prisma.calendarSeason.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CalendarSeasonCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CalendarSeason.
   * @param {CalendarSeasonDeleteArgs} args - Arguments to delete one CalendarSeason.
   * @example
   * // Delete one CalendarSeason
   * const CalendarSeason = await prisma.calendarSeason.delete({
   *   where: {
   *     // ... filter to delete one CalendarSeason
   *   }
   * })
   * 
   */
  delete<T extends CalendarSeasonDeleteArgs>(args: Prisma.SelectSubset<T, CalendarSeasonDeleteArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CalendarSeason.
   * @param {CalendarSeasonUpdateArgs} args - Arguments to update one CalendarSeason.
   * @example
   * // Update one CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CalendarSeasonUpdateArgs>(args: Prisma.SelectSubset<T, CalendarSeasonUpdateArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CalendarSeasons.
   * @param {CalendarSeasonDeleteManyArgs} args - Arguments to filter CalendarSeasons to delete.
   * @example
   * // Delete a few CalendarSeasons
   * const { count } = await prisma.calendarSeason.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CalendarSeasonDeleteManyArgs>(args?: Prisma.SelectSubset<T, CalendarSeasonDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CalendarSeasons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CalendarSeasons
   * const calendarSeason = await prisma.calendarSeason.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CalendarSeasonUpdateManyArgs>(args: Prisma.SelectSubset<T, CalendarSeasonUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CalendarSeasons and returns the data updated in the database.
   * @param {CalendarSeasonUpdateManyAndReturnArgs} args - Arguments to update many CalendarSeasons.
   * @example
   * // Update many CalendarSeasons
   * const calendarSeason = await prisma.calendarSeason.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CalendarSeasons and only return the `id`
   * const calendarSeasonWithIdOnly = await prisma.calendarSeason.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CalendarSeasonUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CalendarSeasonUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CalendarSeason.
   * @param {CalendarSeasonUpsertArgs} args - Arguments to update or create a CalendarSeason.
   * @example
   * // Update or create a CalendarSeason
   * const calendarSeason = await prisma.calendarSeason.upsert({
   *   create: {
   *     // ... data to create a CalendarSeason
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CalendarSeason we want to update
   *   }
   * })
   */
  upsert<T extends CalendarSeasonUpsertArgs>(args: Prisma.SelectSubset<T, CalendarSeasonUpsertArgs<ExtArgs>>): Prisma.Prisma__CalendarSeasonClient<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CalendarSeasons.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonCountArgs} args - Arguments to filter CalendarSeasons to count.
   * @example
   * // Count the number of CalendarSeasons
   * const count = await prisma.calendarSeason.count({
   *   where: {
   *     // ... the filter for the CalendarSeasons we want to count
   *   }
   * })
  **/
  count<T extends CalendarSeasonCountArgs>(
    args?: Prisma.Subset<T, CalendarSeasonCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CalendarSeasonCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CalendarSeason.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CalendarSeasonAggregateArgs>(args: Prisma.Subset<T, CalendarSeasonAggregateArgs>): Prisma.PrismaPromise<GetCalendarSeasonAggregateType<T>>

  /**
   * Group by CalendarSeason.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CalendarSeasonGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CalendarSeasonGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CalendarSeasonGroupByArgs['orderBy'] }
      : { orderBy?: CalendarSeasonGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CalendarSeasonGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCalendarSeasonGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CalendarSeason model
 */
readonly fields: CalendarSeasonFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CalendarSeason.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CalendarSeasonClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  intervals<T extends Prisma.CalendarSeason$intervalsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CalendarSeason$intervalsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CalendarSeasonIntervalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  calendar<T extends Prisma.CalendarDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CalendarDefaultArgs<ExtArgs>>): Prisma.Prisma__CalendarClient<runtime.Types.Result.GetResult<Prisma.$CalendarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CalendarSeason model
 */
export interface CalendarSeasonFieldRefs {
  readonly id: Prisma.FieldRef<"CalendarSeason", 'String'>
  readonly createdAt: Prisma.FieldRef<"CalendarSeason", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CalendarSeason", 'DateTime'>
  readonly position: Prisma.FieldRef<"CalendarSeason", 'Int'>
  readonly name: Prisma.FieldRef<"CalendarSeason", 'String'>
  readonly formatShorthand: Prisma.FieldRef<"CalendarSeason", 'String'>
  readonly calendarId: Prisma.FieldRef<"CalendarSeason", 'String'>
}
    

// Custom InputTypes
/**
 * CalendarSeason findUnique
 */
export type CalendarSeasonFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter, which CalendarSeason to fetch.
   */
  where: Prisma.CalendarSeasonWhereUniqueInput
}

/**
 * CalendarSeason findUniqueOrThrow
 */
export type CalendarSeasonFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter, which CalendarSeason to fetch.
   */
  where: Prisma.CalendarSeasonWhereUniqueInput
}

/**
 * CalendarSeason findFirst
 */
export type CalendarSeasonFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter, which CalendarSeason to fetch.
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarSeasons to fetch.
   */
  orderBy?: Prisma.CalendarSeasonOrderByWithRelationInput | Prisma.CalendarSeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CalendarSeasons.
   */
  cursor?: Prisma.CalendarSeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarSeasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarSeasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CalendarSeasons.
   */
  distinct?: Prisma.CalendarSeasonScalarFieldEnum | Prisma.CalendarSeasonScalarFieldEnum[]
}

/**
 * CalendarSeason findFirstOrThrow
 */
export type CalendarSeasonFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter, which CalendarSeason to fetch.
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarSeasons to fetch.
   */
  orderBy?: Prisma.CalendarSeasonOrderByWithRelationInput | Prisma.CalendarSeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CalendarSeasons.
   */
  cursor?: Prisma.CalendarSeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarSeasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarSeasons.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CalendarSeasons.
   */
  distinct?: Prisma.CalendarSeasonScalarFieldEnum | Prisma.CalendarSeasonScalarFieldEnum[]
}

/**
 * CalendarSeason findMany
 */
export type CalendarSeasonFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter, which CalendarSeasons to fetch.
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CalendarSeasons to fetch.
   */
  orderBy?: Prisma.CalendarSeasonOrderByWithRelationInput | Prisma.CalendarSeasonOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CalendarSeasons.
   */
  cursor?: Prisma.CalendarSeasonWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CalendarSeasons from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CalendarSeasons.
   */
  skip?: number
  distinct?: Prisma.CalendarSeasonScalarFieldEnum | Prisma.CalendarSeasonScalarFieldEnum[]
}

/**
 * CalendarSeason create
 */
export type CalendarSeasonCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * The data needed to create a CalendarSeason.
   */
  data: Prisma.XOR<Prisma.CalendarSeasonCreateInput, Prisma.CalendarSeasonUncheckedCreateInput>
}

/**
 * CalendarSeason createMany
 */
export type CalendarSeasonCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CalendarSeasons.
   */
  data: Prisma.CalendarSeasonCreateManyInput | Prisma.CalendarSeasonCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CalendarSeason createManyAndReturn
 */
export type CalendarSeasonCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * The data used to create many CalendarSeasons.
   */
  data: Prisma.CalendarSeasonCreateManyInput | Prisma.CalendarSeasonCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CalendarSeason update
 */
export type CalendarSeasonUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * The data needed to update a CalendarSeason.
   */
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateInput, Prisma.CalendarSeasonUncheckedUpdateInput>
  /**
   * Choose, which CalendarSeason to update.
   */
  where: Prisma.CalendarSeasonWhereUniqueInput
}

/**
 * CalendarSeason updateMany
 */
export type CalendarSeasonUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CalendarSeasons.
   */
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateManyMutationInput, Prisma.CalendarSeasonUncheckedUpdateManyInput>
  /**
   * Filter which CalendarSeasons to update
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * Limit how many CalendarSeasons to update.
   */
  limit?: number
}

/**
 * CalendarSeason updateManyAndReturn
 */
export type CalendarSeasonUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * The data used to update CalendarSeasons.
   */
  data: Prisma.XOR<Prisma.CalendarSeasonUpdateManyMutationInput, Prisma.CalendarSeasonUncheckedUpdateManyInput>
  /**
   * Filter which CalendarSeasons to update
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * Limit how many CalendarSeasons to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CalendarSeason upsert
 */
export type CalendarSeasonUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * The filter to search for the CalendarSeason to update in case it exists.
   */
  where: Prisma.CalendarSeasonWhereUniqueInput
  /**
   * In case the CalendarSeason found by the `where` argument doesn't exist, create a new CalendarSeason with this data.
   */
  create: Prisma.XOR<Prisma.CalendarSeasonCreateInput, Prisma.CalendarSeasonUncheckedCreateInput>
  /**
   * In case the CalendarSeason was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CalendarSeasonUpdateInput, Prisma.CalendarSeasonUncheckedUpdateInput>
}

/**
 * CalendarSeason delete
 */
export type CalendarSeasonDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
  /**
   * Filter which CalendarSeason to delete.
   */
  where: Prisma.CalendarSeasonWhereUniqueInput
}

/**
 * CalendarSeason deleteMany
 */
export type CalendarSeasonDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CalendarSeasons to delete
   */
  where?: Prisma.CalendarSeasonWhereInput
  /**
   * Limit how many CalendarSeasons to delete.
   */
  limit?: number
}

/**
 * CalendarSeason.intervals
 */
export type CalendarSeason$intervalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeasonInterval
   */
  select?: Prisma.CalendarSeasonIntervalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeasonInterval
   */
  omit?: Prisma.CalendarSeasonIntervalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonIntervalInclude<ExtArgs> | null
  where?: Prisma.CalendarSeasonIntervalWhereInput
  orderBy?: Prisma.CalendarSeasonIntervalOrderByWithRelationInput | Prisma.CalendarSeasonIntervalOrderByWithRelationInput[]
  cursor?: Prisma.CalendarSeasonIntervalWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CalendarSeasonIntervalScalarFieldEnum | Prisma.CalendarSeasonIntervalScalarFieldEnum[]
}

/**
 * CalendarSeason without action
 */
export type CalendarSeasonDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CalendarSeason
   */
  select?: Prisma.CalendarSeasonSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CalendarSeason
   */
  omit?: Prisma.CalendarSeasonOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CalendarSeasonInclude<ExtArgs> | null
}
