
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorldEventTrack` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorldEventTrack
 * 
 */
export type WorldEventTrackModel = runtime.Types.Result.DefaultSelection<Prisma.$WorldEventTrackPayload>

export type AggregateWorldEventTrack = {
  _count: WorldEventTrackCountAggregateOutputType | null
  _avg: WorldEventTrackAvgAggregateOutputType | null
  _sum: WorldEventTrackSumAggregateOutputType | null
  _min: WorldEventTrackMinAggregateOutputType | null
  _max: WorldEventTrackMaxAggregateOutputType | null
}

export type WorldEventTrackAvgAggregateOutputType = {
  position: number | null
}

export type WorldEventTrackSumAggregateOutputType = {
  position: number | null
}

export type WorldEventTrackMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  position: number | null
  visible: boolean | null
  worldId: string | null
}

export type WorldEventTrackMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  name: string | null
  position: number | null
  visible: boolean | null
  worldId: string | null
}

export type WorldEventTrackCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  name: number
  position: number
  visible: number
  worldId: number
  _all: number
}


export type WorldEventTrackAvgAggregateInputType = {
  position?: true
}

export type WorldEventTrackSumAggregateInputType = {
  position?: true
}

export type WorldEventTrackMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  position?: true
  visible?: true
  worldId?: true
}

export type WorldEventTrackMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  position?: true
  visible?: true
  worldId?: true
}

export type WorldEventTrackCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  name?: true
  position?: true
  visible?: true
  worldId?: true
  _all?: true
}

export type WorldEventTrackAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldEventTrack to aggregate.
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventTracks to fetch.
   */
  orderBy?: Prisma.WorldEventTrackOrderByWithRelationInput | Prisma.WorldEventTrackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorldEventTrackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventTracks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventTracks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorldEventTracks
  **/
  _count?: true | WorldEventTrackCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorldEventTrackAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorldEventTrackSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorldEventTrackMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorldEventTrackMaxAggregateInputType
}

export type GetWorldEventTrackAggregateType<T extends WorldEventTrackAggregateArgs> = {
      [P in keyof T & keyof AggregateWorldEventTrack]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorldEventTrack[P]>
    : Prisma.GetScalarType<T[P], AggregateWorldEventTrack[P]>
}




export type WorldEventTrackGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorldEventTrackWhereInput
  orderBy?: Prisma.WorldEventTrackOrderByWithAggregationInput | Prisma.WorldEventTrackOrderByWithAggregationInput[]
  by: Prisma.WorldEventTrackScalarFieldEnum[] | Prisma.WorldEventTrackScalarFieldEnum
  having?: Prisma.WorldEventTrackScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorldEventTrackCountAggregateInputType | true
  _avg?: WorldEventTrackAvgAggregateInputType
  _sum?: WorldEventTrackSumAggregateInputType
  _min?: WorldEventTrackMinAggregateInputType
  _max?: WorldEventTrackMaxAggregateInputType
}

export type WorldEventTrackGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  name: string
  position: number
  visible: boolean
  worldId: string
  _count: WorldEventTrackCountAggregateOutputType | null
  _avg: WorldEventTrackAvgAggregateOutputType | null
  _sum: WorldEventTrackSumAggregateOutputType | null
  _min: WorldEventTrackMinAggregateOutputType | null
  _max: WorldEventTrackMaxAggregateOutputType | null
}

type GetWorldEventTrackGroupByPayload<T extends WorldEventTrackGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorldEventTrackGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorldEventTrackGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorldEventTrackGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorldEventTrackGroupByOutputType[P]>
      }
    >
  >



export type WorldEventTrackWhereInput = {
  AND?: Prisma.WorldEventTrackWhereInput | Prisma.WorldEventTrackWhereInput[]
  OR?: Prisma.WorldEventTrackWhereInput[]
  NOT?: Prisma.WorldEventTrackWhereInput | Prisma.WorldEventTrackWhereInput[]
  id?: Prisma.StringFilter<"WorldEventTrack"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  name?: Prisma.StringFilter<"WorldEventTrack"> | string
  position?: Prisma.IntFilter<"WorldEventTrack"> | number
  visible?: Prisma.BoolFilter<"WorldEventTrack"> | boolean
  worldId?: Prisma.StringFilter<"WorldEventTrack"> | string
  events?: Prisma.WorldEventListRelationFilter
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}

export type WorldEventTrackOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  position?: Prisma.SortOrder
  visible?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  events?: Prisma.WorldEventOrderByRelationAggregateInput
  world?: Prisma.WorldOrderByWithRelationInput
}

export type WorldEventTrackWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorldEventTrackWhereInput | Prisma.WorldEventTrackWhereInput[]
  OR?: Prisma.WorldEventTrackWhereInput[]
  NOT?: Prisma.WorldEventTrackWhereInput | Prisma.WorldEventTrackWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  name?: Prisma.StringFilter<"WorldEventTrack"> | string
  position?: Prisma.IntFilter<"WorldEventTrack"> | number
  visible?: Prisma.BoolFilter<"WorldEventTrack"> | boolean
  worldId?: Prisma.StringFilter<"WorldEventTrack"> | string
  events?: Prisma.WorldEventListRelationFilter
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}, "id" | "id">

export type WorldEventTrackOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  position?: Prisma.SortOrder
  visible?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  _count?: Prisma.WorldEventTrackCountOrderByAggregateInput
  _avg?: Prisma.WorldEventTrackAvgOrderByAggregateInput
  _max?: Prisma.WorldEventTrackMaxOrderByAggregateInput
  _min?: Prisma.WorldEventTrackMinOrderByAggregateInput
  _sum?: Prisma.WorldEventTrackSumOrderByAggregateInput
}

export type WorldEventTrackScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorldEventTrackScalarWhereWithAggregatesInput | Prisma.WorldEventTrackScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorldEventTrackScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorldEventTrackScalarWhereWithAggregatesInput | Prisma.WorldEventTrackScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorldEventTrack"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorldEventTrack"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorldEventTrack"> | Date | string
  name?: Prisma.StringWithAggregatesFilter<"WorldEventTrack"> | string
  position?: Prisma.IntWithAggregatesFilter<"WorldEventTrack"> | number
  visible?: Prisma.BoolWithAggregatesFilter<"WorldEventTrack"> | boolean
  worldId?: Prisma.StringWithAggregatesFilter<"WorldEventTrack"> | string
}

export type WorldEventTrackCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  events?: Prisma.WorldEventCreateNestedManyWithoutTrackInput
  world: Prisma.WorldCreateNestedOneWithoutWorldEventTracksInput
}

export type WorldEventTrackUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  worldId: string
  events?: Prisma.WorldEventUncheckedCreateNestedManyWithoutTrackInput
}

export type WorldEventTrackUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  events?: Prisma.WorldEventUpdateManyWithoutTrackNestedInput
  world?: Prisma.WorldUpdateOneRequiredWithoutWorldEventTracksNestedInput
}

export type WorldEventTrackUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
  events?: Prisma.WorldEventUncheckedUpdateManyWithoutTrackNestedInput
}

export type WorldEventTrackCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  worldId: string
}

export type WorldEventTrackUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type WorldEventTrackUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldEventTrackListRelationFilter = {
  every?: Prisma.WorldEventTrackWhereInput
  some?: Prisma.WorldEventTrackWhereInput
  none?: Prisma.WorldEventTrackWhereInput
}

export type WorldEventTrackOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorldEventTrackNullableScalarRelationFilter = {
  is?: Prisma.WorldEventTrackWhereInput | null
  isNot?: Prisma.WorldEventTrackWhereInput | null
}

export type WorldEventTrackCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  position?: Prisma.SortOrder
  visible?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldEventTrackAvgOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type WorldEventTrackMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  position?: Prisma.SortOrder
  visible?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldEventTrackMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  name?: Prisma.SortOrder
  position?: Prisma.SortOrder
  visible?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldEventTrackSumOrderByAggregateInput = {
  position?: Prisma.SortOrder
}

export type WorldEventTrackCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput> | Prisma.WorldEventTrackCreateWithoutWorldInput[] | Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput | Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.WorldEventTrackCreateManyWorldInputEnvelope
  connect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
}

export type WorldEventTrackUncheckedCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput> | Prisma.WorldEventTrackCreateWithoutWorldInput[] | Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput | Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.WorldEventTrackCreateManyWorldInputEnvelope
  connect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
}

export type WorldEventTrackUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput> | Prisma.WorldEventTrackCreateWithoutWorldInput[] | Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput | Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.WorldEventTrackUpsertWithWhereUniqueWithoutWorldInput | Prisma.WorldEventTrackUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.WorldEventTrackCreateManyWorldInputEnvelope
  set?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  disconnect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  delete?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  connect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  update?: Prisma.WorldEventTrackUpdateWithWhereUniqueWithoutWorldInput | Prisma.WorldEventTrackUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.WorldEventTrackUpdateManyWithWhereWithoutWorldInput | Prisma.WorldEventTrackUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.WorldEventTrackScalarWhereInput | Prisma.WorldEventTrackScalarWhereInput[]
}

export type WorldEventTrackUncheckedUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput> | Prisma.WorldEventTrackCreateWithoutWorldInput[] | Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput | Prisma.WorldEventTrackCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.WorldEventTrackUpsertWithWhereUniqueWithoutWorldInput | Prisma.WorldEventTrackUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.WorldEventTrackCreateManyWorldInputEnvelope
  set?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  disconnect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  delete?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  connect?: Prisma.WorldEventTrackWhereUniqueInput | Prisma.WorldEventTrackWhereUniqueInput[]
  update?: Prisma.WorldEventTrackUpdateWithWhereUniqueWithoutWorldInput | Prisma.WorldEventTrackUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.WorldEventTrackUpdateManyWithWhereWithoutWorldInput | Prisma.WorldEventTrackUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.WorldEventTrackScalarWhereInput | Prisma.WorldEventTrackScalarWhereInput[]
}

export type WorldEventTrackCreateNestedOneWithoutEventsInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutEventsInput, Prisma.WorldEventTrackUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutEventsInput
  connect?: Prisma.WorldEventTrackWhereUniqueInput
}

export type WorldEventTrackUpdateOneWithoutEventsNestedInput = {
  create?: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutEventsInput, Prisma.WorldEventTrackUncheckedCreateWithoutEventsInput>
  connectOrCreate?: Prisma.WorldEventTrackCreateOrConnectWithoutEventsInput
  upsert?: Prisma.WorldEventTrackUpsertWithoutEventsInput
  disconnect?: Prisma.WorldEventTrackWhereInput | boolean
  delete?: Prisma.WorldEventTrackWhereInput | boolean
  connect?: Prisma.WorldEventTrackWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorldEventTrackUpdateToOneWithWhereWithoutEventsInput, Prisma.WorldEventTrackUpdateWithoutEventsInput>, Prisma.WorldEventTrackUncheckedUpdateWithoutEventsInput>
}

export type WorldEventTrackCreateWithoutWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  events?: Prisma.WorldEventCreateNestedManyWithoutTrackInput
}

export type WorldEventTrackUncheckedCreateWithoutWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  events?: Prisma.WorldEventUncheckedCreateNestedManyWithoutTrackInput
}

export type WorldEventTrackCreateOrConnectWithoutWorldInput = {
  where: Prisma.WorldEventTrackWhereUniqueInput
  create: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput>
}

export type WorldEventTrackCreateManyWorldInputEnvelope = {
  data: Prisma.WorldEventTrackCreateManyWorldInput | Prisma.WorldEventTrackCreateManyWorldInput[]
  skipDuplicates?: boolean
}

export type WorldEventTrackUpsertWithWhereUniqueWithoutWorldInput = {
  where: Prisma.WorldEventTrackWhereUniqueInput
  update: Prisma.XOR<Prisma.WorldEventTrackUpdateWithoutWorldInput, Prisma.WorldEventTrackUncheckedUpdateWithoutWorldInput>
  create: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutWorldInput, Prisma.WorldEventTrackUncheckedCreateWithoutWorldInput>
}

export type WorldEventTrackUpdateWithWhereUniqueWithoutWorldInput = {
  where: Prisma.WorldEventTrackWhereUniqueInput
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateWithoutWorldInput, Prisma.WorldEventTrackUncheckedUpdateWithoutWorldInput>
}

export type WorldEventTrackUpdateManyWithWhereWithoutWorldInput = {
  where: Prisma.WorldEventTrackScalarWhereInput
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateManyMutationInput, Prisma.WorldEventTrackUncheckedUpdateManyWithoutWorldInput>
}

export type WorldEventTrackScalarWhereInput = {
  AND?: Prisma.WorldEventTrackScalarWhereInput | Prisma.WorldEventTrackScalarWhereInput[]
  OR?: Prisma.WorldEventTrackScalarWhereInput[]
  NOT?: Prisma.WorldEventTrackScalarWhereInput | Prisma.WorldEventTrackScalarWhereInput[]
  id?: Prisma.StringFilter<"WorldEventTrack"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventTrack"> | Date | string
  name?: Prisma.StringFilter<"WorldEventTrack"> | string
  position?: Prisma.IntFilter<"WorldEventTrack"> | number
  visible?: Prisma.BoolFilter<"WorldEventTrack"> | boolean
  worldId?: Prisma.StringFilter<"WorldEventTrack"> | string
}

export type WorldEventTrackCreateWithoutEventsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  world: Prisma.WorldCreateNestedOneWithoutWorldEventTracksInput
}

export type WorldEventTrackUncheckedCreateWithoutEventsInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
  worldId: string
}

export type WorldEventTrackCreateOrConnectWithoutEventsInput = {
  where: Prisma.WorldEventTrackWhereUniqueInput
  create: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutEventsInput, Prisma.WorldEventTrackUncheckedCreateWithoutEventsInput>
}

export type WorldEventTrackUpsertWithoutEventsInput = {
  update: Prisma.XOR<Prisma.WorldEventTrackUpdateWithoutEventsInput, Prisma.WorldEventTrackUncheckedUpdateWithoutEventsInput>
  create: Prisma.XOR<Prisma.WorldEventTrackCreateWithoutEventsInput, Prisma.WorldEventTrackUncheckedCreateWithoutEventsInput>
  where?: Prisma.WorldEventTrackWhereInput
}

export type WorldEventTrackUpdateToOneWithWhereWithoutEventsInput = {
  where?: Prisma.WorldEventTrackWhereInput
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateWithoutEventsInput, Prisma.WorldEventTrackUncheckedUpdateWithoutEventsInput>
}

export type WorldEventTrackUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  world?: Prisma.WorldUpdateOneRequiredWithoutWorldEventTracksNestedInput
}

export type WorldEventTrackUncheckedUpdateWithoutEventsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldEventTrackCreateManyWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  name: string
  position: number
  visible?: boolean
}

export type WorldEventTrackUpdateWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  events?: Prisma.WorldEventUpdateManyWithoutTrackNestedInput
}

export type WorldEventTrackUncheckedUpdateWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
  events?: Prisma.WorldEventUncheckedUpdateManyWithoutTrackNestedInput
}

export type WorldEventTrackUncheckedUpdateManyWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  position?: Prisma.IntFieldUpdateOperationsInput | number
  visible?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type WorldEventTrackCountOutputType
 */

export type WorldEventTrackCountOutputType = {
  events: number
}

export type WorldEventTrackCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | WorldEventTrackCountOutputTypeCountEventsArgs
}

/**
 * WorldEventTrackCountOutputType without action
 */
export type WorldEventTrackCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrackCountOutputType
   */
  select?: Prisma.WorldEventTrackCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorldEventTrackCountOutputType without action
 */
export type WorldEventTrackCountOutputTypeCountEventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorldEventWhereInput
}


export type WorldEventTrackSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  position?: boolean
  visible?: boolean
  worldId?: boolean
  events?: boolean | Prisma.WorldEventTrack$eventsArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.WorldEventTrackCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventTrack"]>

export type WorldEventTrackSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  position?: boolean
  visible?: boolean
  worldId?: boolean
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventTrack"]>

export type WorldEventTrackSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  position?: boolean
  visible?: boolean
  worldId?: boolean
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventTrack"]>

export type WorldEventTrackSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  name?: boolean
  position?: boolean
  visible?: boolean
  worldId?: boolean
}

export type WorldEventTrackOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "name" | "position" | "visible" | "worldId", ExtArgs["result"]["worldEventTrack"]>
export type WorldEventTrackInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  events?: boolean | Prisma.WorldEventTrack$eventsArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.WorldEventTrackCountOutputTypeDefaultArgs<ExtArgs>
}
export type WorldEventTrackIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}
export type WorldEventTrackIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}

export type $WorldEventTrackPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorldEventTrack"
  objects: {
    events: Prisma.$WorldEventPayload<ExtArgs>[]
    world: Prisma.$WorldPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    name: string
    position: number
    visible: boolean
    worldId: string
  }, ExtArgs["result"]["worldEventTrack"]>
  composites: {}
}

export type WorldEventTrackGetPayload<S extends boolean | null | undefined | WorldEventTrackDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload, S>

export type WorldEventTrackCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorldEventTrackFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorldEventTrackCountAggregateInputType | true
  }

export interface WorldEventTrackDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorldEventTrack'], meta: { name: 'WorldEventTrack' } }
  /**
   * Find zero or one WorldEventTrack that matches the filter.
   * @param {WorldEventTrackFindUniqueArgs} args - Arguments to find a WorldEventTrack
   * @example
   * // Get one WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorldEventTrackFindUniqueArgs>(args: Prisma.SelectSubset<T, WorldEventTrackFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorldEventTrack that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorldEventTrackFindUniqueOrThrowArgs} args - Arguments to find a WorldEventTrack
   * @example
   * // Get one WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorldEventTrackFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorldEventTrackFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldEventTrack that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackFindFirstArgs} args - Arguments to find a WorldEventTrack
   * @example
   * // Get one WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorldEventTrackFindFirstArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldEventTrack that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackFindFirstOrThrowArgs} args - Arguments to find a WorldEventTrack
   * @example
   * // Get one WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorldEventTrackFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorldEventTracks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorldEventTracks
   * const worldEventTracks = await prisma.worldEventTrack.findMany()
   * 
   * // Get first 10 WorldEventTracks
   * const worldEventTracks = await prisma.worldEventTrack.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const worldEventTrackWithIdOnly = await prisma.worldEventTrack.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorldEventTrackFindManyArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorldEventTrack.
   * @param {WorldEventTrackCreateArgs} args - Arguments to create a WorldEventTrack.
   * @example
   * // Create one WorldEventTrack
   * const WorldEventTrack = await prisma.worldEventTrack.create({
   *   data: {
   *     // ... data to create a WorldEventTrack
   *   }
   * })
   * 
   */
  create<T extends WorldEventTrackCreateArgs>(args: Prisma.SelectSubset<T, WorldEventTrackCreateArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorldEventTracks.
   * @param {WorldEventTrackCreateManyArgs} args - Arguments to create many WorldEventTracks.
   * @example
   * // Create many WorldEventTracks
   * const worldEventTrack = await prisma.worldEventTrack.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorldEventTrackCreateManyArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorldEventTracks and returns the data saved in the database.
   * @param {WorldEventTrackCreateManyAndReturnArgs} args - Arguments to create many WorldEventTracks.
   * @example
   * // Create many WorldEventTracks
   * const worldEventTrack = await prisma.worldEventTrack.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorldEventTracks and only return the `id`
   * const worldEventTrackWithIdOnly = await prisma.worldEventTrack.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorldEventTrackCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorldEventTrack.
   * @param {WorldEventTrackDeleteArgs} args - Arguments to delete one WorldEventTrack.
   * @example
   * // Delete one WorldEventTrack
   * const WorldEventTrack = await prisma.worldEventTrack.delete({
   *   where: {
   *     // ... filter to delete one WorldEventTrack
   *   }
   * })
   * 
   */
  delete<T extends WorldEventTrackDeleteArgs>(args: Prisma.SelectSubset<T, WorldEventTrackDeleteArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorldEventTrack.
   * @param {WorldEventTrackUpdateArgs} args - Arguments to update one WorldEventTrack.
   * @example
   * // Update one WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorldEventTrackUpdateArgs>(args: Prisma.SelectSubset<T, WorldEventTrackUpdateArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorldEventTracks.
   * @param {WorldEventTrackDeleteManyArgs} args - Arguments to filter WorldEventTracks to delete.
   * @example
   * // Delete a few WorldEventTracks
   * const { count } = await prisma.worldEventTrack.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorldEventTrackDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorldEventTrackDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldEventTracks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorldEventTracks
   * const worldEventTrack = await prisma.worldEventTrack.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorldEventTrackUpdateManyArgs>(args: Prisma.SelectSubset<T, WorldEventTrackUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldEventTracks and returns the data updated in the database.
   * @param {WorldEventTrackUpdateManyAndReturnArgs} args - Arguments to update many WorldEventTracks.
   * @example
   * // Update many WorldEventTracks
   * const worldEventTrack = await prisma.worldEventTrack.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorldEventTracks and only return the `id`
   * const worldEventTrackWithIdOnly = await prisma.worldEventTrack.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorldEventTrackUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorldEventTrackUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorldEventTrack.
   * @param {WorldEventTrackUpsertArgs} args - Arguments to update or create a WorldEventTrack.
   * @example
   * // Update or create a WorldEventTrack
   * const worldEventTrack = await prisma.worldEventTrack.upsert({
   *   create: {
   *     // ... data to create a WorldEventTrack
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorldEventTrack we want to update
   *   }
   * })
   */
  upsert<T extends WorldEventTrackUpsertArgs>(args: Prisma.SelectSubset<T, WorldEventTrackUpsertArgs<ExtArgs>>): Prisma.Prisma__WorldEventTrackClient<runtime.Types.Result.GetResult<Prisma.$WorldEventTrackPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorldEventTracks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackCountArgs} args - Arguments to filter WorldEventTracks to count.
   * @example
   * // Count the number of WorldEventTracks
   * const count = await prisma.worldEventTrack.count({
   *   where: {
   *     // ... the filter for the WorldEventTracks we want to count
   *   }
   * })
  **/
  count<T extends WorldEventTrackCountArgs>(
    args?: Prisma.Subset<T, WorldEventTrackCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorldEventTrackCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorldEventTrack.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorldEventTrackAggregateArgs>(args: Prisma.Subset<T, WorldEventTrackAggregateArgs>): Prisma.PrismaPromise<GetWorldEventTrackAggregateType<T>>

  /**
   * Group by WorldEventTrack.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventTrackGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorldEventTrackGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorldEventTrackGroupByArgs['orderBy'] }
      : { orderBy?: WorldEventTrackGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorldEventTrackGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorldEventTrackGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorldEventTrack model
 */
readonly fields: WorldEventTrackFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorldEventTrack.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorldEventTrackClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  events<T extends Prisma.WorldEventTrack$eventsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorldEventTrack$eventsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  world<T extends Prisma.WorldDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorldDefaultArgs<ExtArgs>>): Prisma.Prisma__WorldClient<runtime.Types.Result.GetResult<Prisma.$WorldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorldEventTrack model
 */
export interface WorldEventTrackFieldRefs {
  readonly id: Prisma.FieldRef<"WorldEventTrack", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorldEventTrack", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorldEventTrack", 'DateTime'>
  readonly name: Prisma.FieldRef<"WorldEventTrack", 'String'>
  readonly position: Prisma.FieldRef<"WorldEventTrack", 'Int'>
  readonly visible: Prisma.FieldRef<"WorldEventTrack", 'Boolean'>
  readonly worldId: Prisma.FieldRef<"WorldEventTrack", 'String'>
}
    

// Custom InputTypes
/**
 * WorldEventTrack findUnique
 */
export type WorldEventTrackFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventTrack to fetch.
   */
  where: Prisma.WorldEventTrackWhereUniqueInput
}

/**
 * WorldEventTrack findUniqueOrThrow
 */
export type WorldEventTrackFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventTrack to fetch.
   */
  where: Prisma.WorldEventTrackWhereUniqueInput
}

/**
 * WorldEventTrack findFirst
 */
export type WorldEventTrackFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventTrack to fetch.
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventTracks to fetch.
   */
  orderBy?: Prisma.WorldEventTrackOrderByWithRelationInput | Prisma.WorldEventTrackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldEventTracks.
   */
  cursor?: Prisma.WorldEventTrackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventTracks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventTracks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldEventTracks.
   */
  distinct?: Prisma.WorldEventTrackScalarFieldEnum | Prisma.WorldEventTrackScalarFieldEnum[]
}

/**
 * WorldEventTrack findFirstOrThrow
 */
export type WorldEventTrackFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventTrack to fetch.
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventTracks to fetch.
   */
  orderBy?: Prisma.WorldEventTrackOrderByWithRelationInput | Prisma.WorldEventTrackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldEventTracks.
   */
  cursor?: Prisma.WorldEventTrackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventTracks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventTracks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldEventTracks.
   */
  distinct?: Prisma.WorldEventTrackScalarFieldEnum | Prisma.WorldEventTrackScalarFieldEnum[]
}

/**
 * WorldEventTrack findMany
 */
export type WorldEventTrackFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventTracks to fetch.
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventTracks to fetch.
   */
  orderBy?: Prisma.WorldEventTrackOrderByWithRelationInput | Prisma.WorldEventTrackOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorldEventTracks.
   */
  cursor?: Prisma.WorldEventTrackWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventTracks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventTracks.
   */
  skip?: number
  distinct?: Prisma.WorldEventTrackScalarFieldEnum | Prisma.WorldEventTrackScalarFieldEnum[]
}

/**
 * WorldEventTrack create
 */
export type WorldEventTrackCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * The data needed to create a WorldEventTrack.
   */
  data: Prisma.XOR<Prisma.WorldEventTrackCreateInput, Prisma.WorldEventTrackUncheckedCreateInput>
}

/**
 * WorldEventTrack createMany
 */
export type WorldEventTrackCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorldEventTracks.
   */
  data: Prisma.WorldEventTrackCreateManyInput | Prisma.WorldEventTrackCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorldEventTrack createManyAndReturn
 */
export type WorldEventTrackCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * The data used to create many WorldEventTracks.
   */
  data: Prisma.WorldEventTrackCreateManyInput | Prisma.WorldEventTrackCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorldEventTrack update
 */
export type WorldEventTrackUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * The data needed to update a WorldEventTrack.
   */
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateInput, Prisma.WorldEventTrackUncheckedUpdateInput>
  /**
   * Choose, which WorldEventTrack to update.
   */
  where: Prisma.WorldEventTrackWhereUniqueInput
}

/**
 * WorldEventTrack updateMany
 */
export type WorldEventTrackUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorldEventTracks.
   */
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateManyMutationInput, Prisma.WorldEventTrackUncheckedUpdateManyInput>
  /**
   * Filter which WorldEventTracks to update
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * Limit how many WorldEventTracks to update.
   */
  limit?: number
}

/**
 * WorldEventTrack updateManyAndReturn
 */
export type WorldEventTrackUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * The data used to update WorldEventTracks.
   */
  data: Prisma.XOR<Prisma.WorldEventTrackUpdateManyMutationInput, Prisma.WorldEventTrackUncheckedUpdateManyInput>
  /**
   * Filter which WorldEventTracks to update
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * Limit how many WorldEventTracks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorldEventTrack upsert
 */
export type WorldEventTrackUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * The filter to search for the WorldEventTrack to update in case it exists.
   */
  where: Prisma.WorldEventTrackWhereUniqueInput
  /**
   * In case the WorldEventTrack found by the `where` argument doesn't exist, create a new WorldEventTrack with this data.
   */
  create: Prisma.XOR<Prisma.WorldEventTrackCreateInput, Prisma.WorldEventTrackUncheckedCreateInput>
  /**
   * In case the WorldEventTrack was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorldEventTrackUpdateInput, Prisma.WorldEventTrackUncheckedUpdateInput>
}

/**
 * WorldEventTrack delete
 */
export type WorldEventTrackDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
  /**
   * Filter which WorldEventTrack to delete.
   */
  where: Prisma.WorldEventTrackWhereUniqueInput
}

/**
 * WorldEventTrack deleteMany
 */
export type WorldEventTrackDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldEventTracks to delete
   */
  where?: Prisma.WorldEventTrackWhereInput
  /**
   * Limit how many WorldEventTracks to delete.
   */
  limit?: number
}

/**
 * WorldEventTrack.events
 */
export type WorldEventTrack$eventsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEvent
   */
  select?: Prisma.WorldEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEvent
   */
  omit?: Prisma.WorldEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventInclude<ExtArgs> | null
  where?: Prisma.WorldEventWhereInput
  orderBy?: Prisma.WorldEventOrderByWithRelationInput | Prisma.WorldEventOrderByWithRelationInput[]
  cursor?: Prisma.WorldEventWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorldEventScalarFieldEnum | Prisma.WorldEventScalarFieldEnum[]
}

/**
 * WorldEventTrack without action
 */
export type WorldEventTrackDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventTrack
   */
  select?: Prisma.WorldEventTrackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventTrack
   */
  omit?: Prisma.WorldEventTrackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventTrackInclude<ExtArgs> | null
}
