
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorldEventDelta` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorldEventDelta
 * 
 */
export type WorldEventDeltaModel = runtime.Types.Result.DefaultSelection<Prisma.$WorldEventDeltaPayload>

export type AggregateWorldEventDelta = {
  _count: WorldEventDeltaCountAggregateOutputType | null
  _avg: WorldEventDeltaAvgAggregateOutputType | null
  _sum: WorldEventDeltaSumAggregateOutputType | null
  _min: WorldEventDeltaMinAggregateOutputType | null
  _max: WorldEventDeltaMaxAggregateOutputType | null
}

export type WorldEventDeltaAvgAggregateOutputType = {
  timestamp: number | null
}

export type WorldEventDeltaSumAggregateOutputType = {
  timestamp: bigint | null
}

export type WorldEventDeltaMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  timestamp: bigint | null
  name: string | null
  description: string | null
  descriptionRich: string | null
  worldEventId: string | null
}

export type WorldEventDeltaMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  timestamp: bigint | null
  name: string | null
  description: string | null
  descriptionRich: string | null
  worldEventId: string | null
}

export type WorldEventDeltaCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  timestamp: number
  name: number
  description: number
  descriptionRich: number
  worldEventId: number
  _all: number
}


export type WorldEventDeltaAvgAggregateInputType = {
  timestamp?: true
}

export type WorldEventDeltaSumAggregateInputType = {
  timestamp?: true
}

export type WorldEventDeltaMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  timestamp?: true
  name?: true
  description?: true
  descriptionRich?: true
  worldEventId?: true
}

export type WorldEventDeltaMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  timestamp?: true
  name?: true
  description?: true
  descriptionRich?: true
  worldEventId?: true
}

export type WorldEventDeltaCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  timestamp?: true
  name?: true
  description?: true
  descriptionRich?: true
  worldEventId?: true
  _all?: true
}

export type WorldEventDeltaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldEventDelta to aggregate.
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventDeltas to fetch.
   */
  orderBy?: Prisma.WorldEventDeltaOrderByWithRelationInput | Prisma.WorldEventDeltaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorldEventDeltaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventDeltas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventDeltas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorldEventDeltas
  **/
  _count?: true | WorldEventDeltaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorldEventDeltaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorldEventDeltaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorldEventDeltaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorldEventDeltaMaxAggregateInputType
}

export type GetWorldEventDeltaAggregateType<T extends WorldEventDeltaAggregateArgs> = {
      [P in keyof T & keyof AggregateWorldEventDelta]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorldEventDelta[P]>
    : Prisma.GetScalarType<T[P], AggregateWorldEventDelta[P]>
}




export type WorldEventDeltaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorldEventDeltaWhereInput
  orderBy?: Prisma.WorldEventDeltaOrderByWithAggregationInput | Prisma.WorldEventDeltaOrderByWithAggregationInput[]
  by: Prisma.WorldEventDeltaScalarFieldEnum[] | Prisma.WorldEventDeltaScalarFieldEnum
  having?: Prisma.WorldEventDeltaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorldEventDeltaCountAggregateInputType | true
  _avg?: WorldEventDeltaAvgAggregateInputType
  _sum?: WorldEventDeltaSumAggregateInputType
  _min?: WorldEventDeltaMinAggregateInputType
  _max?: WorldEventDeltaMaxAggregateInputType
}

export type WorldEventDeltaGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  timestamp: bigint
  name: string | null
  description: string | null
  descriptionRich: string | null
  worldEventId: string
  _count: WorldEventDeltaCountAggregateOutputType | null
  _avg: WorldEventDeltaAvgAggregateOutputType | null
  _sum: WorldEventDeltaSumAggregateOutputType | null
  _min: WorldEventDeltaMinAggregateOutputType | null
  _max: WorldEventDeltaMaxAggregateOutputType | null
}

type GetWorldEventDeltaGroupByPayload<T extends WorldEventDeltaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorldEventDeltaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorldEventDeltaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorldEventDeltaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorldEventDeltaGroupByOutputType[P]>
      }
    >
  >



export type WorldEventDeltaWhereInput = {
  AND?: Prisma.WorldEventDeltaWhereInput | Prisma.WorldEventDeltaWhereInput[]
  OR?: Prisma.WorldEventDeltaWhereInput[]
  NOT?: Prisma.WorldEventDeltaWhereInput | Prisma.WorldEventDeltaWhereInput[]
  id?: Prisma.StringFilter<"WorldEventDelta"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  timestamp?: Prisma.BigIntFilter<"WorldEventDelta"> | bigint | number
  name?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  description?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  descriptionRich?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  worldEventId?: Prisma.StringFilter<"WorldEventDelta"> | string
  worldEvent?: Prisma.XOR<Prisma.WorldEventScalarRelationFilter, Prisma.WorldEventWhereInput>
}

export type WorldEventDeltaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  descriptionRich?: Prisma.SortOrderInput | Prisma.SortOrder
  worldEventId?: Prisma.SortOrder
  worldEvent?: Prisma.WorldEventOrderByWithRelationInput
}

export type WorldEventDeltaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorldEventDeltaWhereInput | Prisma.WorldEventDeltaWhereInput[]
  OR?: Prisma.WorldEventDeltaWhereInput[]
  NOT?: Prisma.WorldEventDeltaWhereInput | Prisma.WorldEventDeltaWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  timestamp?: Prisma.BigIntFilter<"WorldEventDelta"> | bigint | number
  name?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  description?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  descriptionRich?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  worldEventId?: Prisma.StringFilter<"WorldEventDelta"> | string
  worldEvent?: Prisma.XOR<Prisma.WorldEventScalarRelationFilter, Prisma.WorldEventWhereInput>
}, "id" | "id">

export type WorldEventDeltaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  descriptionRich?: Prisma.SortOrderInput | Prisma.SortOrder
  worldEventId?: Prisma.SortOrder
  _count?: Prisma.WorldEventDeltaCountOrderByAggregateInput
  _avg?: Prisma.WorldEventDeltaAvgOrderByAggregateInput
  _max?: Prisma.WorldEventDeltaMaxOrderByAggregateInput
  _min?: Prisma.WorldEventDeltaMinOrderByAggregateInput
  _sum?: Prisma.WorldEventDeltaSumOrderByAggregateInput
}

export type WorldEventDeltaScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorldEventDeltaScalarWhereWithAggregatesInput | Prisma.WorldEventDeltaScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorldEventDeltaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorldEventDeltaScalarWhereWithAggregatesInput | Prisma.WorldEventDeltaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorldEventDelta"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorldEventDelta"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorldEventDelta"> | Date | string
  timestamp?: Prisma.BigIntWithAggregatesFilter<"WorldEventDelta"> | bigint | number
  name?: Prisma.StringNullableWithAggregatesFilter<"WorldEventDelta"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"WorldEventDelta"> | string | null
  descriptionRich?: Prisma.StringNullableWithAggregatesFilter<"WorldEventDelta"> | string | null
  worldEventId?: Prisma.StringWithAggregatesFilter<"WorldEventDelta"> | string
}

export type WorldEventDeltaCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
  worldEvent: Prisma.WorldEventCreateNestedOneWithoutDeltaStatesInput
}

export type WorldEventDeltaUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
  worldEventId: string
}

export type WorldEventDeltaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  worldEvent?: Prisma.WorldEventUpdateOneRequiredWithoutDeltaStatesNestedInput
}

export type WorldEventDeltaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  worldEventId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldEventDeltaCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
  worldEventId: string
}

export type WorldEventDeltaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorldEventDeltaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  worldEventId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldEventDeltaListRelationFilter = {
  every?: Prisma.WorldEventDeltaWhereInput
  some?: Prisma.WorldEventDeltaWhereInput
  none?: Prisma.WorldEventDeltaWhereInput
}

export type WorldEventDeltaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorldEventDeltaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  descriptionRich?: Prisma.SortOrder
  worldEventId?: Prisma.SortOrder
}

export type WorldEventDeltaAvgOrderByAggregateInput = {
  timestamp?: Prisma.SortOrder
}

export type WorldEventDeltaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  descriptionRich?: Prisma.SortOrder
  worldEventId?: Prisma.SortOrder
}

export type WorldEventDeltaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  descriptionRich?: Prisma.SortOrder
  worldEventId?: Prisma.SortOrder
}

export type WorldEventDeltaSumOrderByAggregateInput = {
  timestamp?: Prisma.SortOrder
}

export type WorldEventDeltaCreateNestedManyWithoutWorldEventInput = {
  create?: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput> | Prisma.WorldEventDeltaCreateWithoutWorldEventInput[] | Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput[]
  connectOrCreate?: Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput | Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput[]
  createMany?: Prisma.WorldEventDeltaCreateManyWorldEventInputEnvelope
  connect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
}

export type WorldEventDeltaUncheckedCreateNestedManyWithoutWorldEventInput = {
  create?: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput> | Prisma.WorldEventDeltaCreateWithoutWorldEventInput[] | Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput[]
  connectOrCreate?: Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput | Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput[]
  createMany?: Prisma.WorldEventDeltaCreateManyWorldEventInputEnvelope
  connect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
}

export type WorldEventDeltaUpdateManyWithoutWorldEventNestedInput = {
  create?: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput> | Prisma.WorldEventDeltaCreateWithoutWorldEventInput[] | Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput[]
  connectOrCreate?: Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput | Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput[]
  upsert?: Prisma.WorldEventDeltaUpsertWithWhereUniqueWithoutWorldEventInput | Prisma.WorldEventDeltaUpsertWithWhereUniqueWithoutWorldEventInput[]
  createMany?: Prisma.WorldEventDeltaCreateManyWorldEventInputEnvelope
  set?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  disconnect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  delete?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  connect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  update?: Prisma.WorldEventDeltaUpdateWithWhereUniqueWithoutWorldEventInput | Prisma.WorldEventDeltaUpdateWithWhereUniqueWithoutWorldEventInput[]
  updateMany?: Prisma.WorldEventDeltaUpdateManyWithWhereWithoutWorldEventInput | Prisma.WorldEventDeltaUpdateManyWithWhereWithoutWorldEventInput[]
  deleteMany?: Prisma.WorldEventDeltaScalarWhereInput | Prisma.WorldEventDeltaScalarWhereInput[]
}

export type WorldEventDeltaUncheckedUpdateManyWithoutWorldEventNestedInput = {
  create?: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput> | Prisma.WorldEventDeltaCreateWithoutWorldEventInput[] | Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput[]
  connectOrCreate?: Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput | Prisma.WorldEventDeltaCreateOrConnectWithoutWorldEventInput[]
  upsert?: Prisma.WorldEventDeltaUpsertWithWhereUniqueWithoutWorldEventInput | Prisma.WorldEventDeltaUpsertWithWhereUniqueWithoutWorldEventInput[]
  createMany?: Prisma.WorldEventDeltaCreateManyWorldEventInputEnvelope
  set?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  disconnect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  delete?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  connect?: Prisma.WorldEventDeltaWhereUniqueInput | Prisma.WorldEventDeltaWhereUniqueInput[]
  update?: Prisma.WorldEventDeltaUpdateWithWhereUniqueWithoutWorldEventInput | Prisma.WorldEventDeltaUpdateWithWhereUniqueWithoutWorldEventInput[]
  updateMany?: Prisma.WorldEventDeltaUpdateManyWithWhereWithoutWorldEventInput | Prisma.WorldEventDeltaUpdateManyWithWhereWithoutWorldEventInput[]
  deleteMany?: Prisma.WorldEventDeltaScalarWhereInput | Prisma.WorldEventDeltaScalarWhereInput[]
}

export type WorldEventDeltaCreateWithoutWorldEventInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
}

export type WorldEventDeltaUncheckedCreateWithoutWorldEventInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
}

export type WorldEventDeltaCreateOrConnectWithoutWorldEventInput = {
  where: Prisma.WorldEventDeltaWhereUniqueInput
  create: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput>
}

export type WorldEventDeltaCreateManyWorldEventInputEnvelope = {
  data: Prisma.WorldEventDeltaCreateManyWorldEventInput | Prisma.WorldEventDeltaCreateManyWorldEventInput[]
  skipDuplicates?: boolean
}

export type WorldEventDeltaUpsertWithWhereUniqueWithoutWorldEventInput = {
  where: Prisma.WorldEventDeltaWhereUniqueInput
  update: Prisma.XOR<Prisma.WorldEventDeltaUpdateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedUpdateWithoutWorldEventInput>
  create: Prisma.XOR<Prisma.WorldEventDeltaCreateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedCreateWithoutWorldEventInput>
}

export type WorldEventDeltaUpdateWithWhereUniqueWithoutWorldEventInput = {
  where: Prisma.WorldEventDeltaWhereUniqueInput
  data: Prisma.XOR<Prisma.WorldEventDeltaUpdateWithoutWorldEventInput, Prisma.WorldEventDeltaUncheckedUpdateWithoutWorldEventInput>
}

export type WorldEventDeltaUpdateManyWithWhereWithoutWorldEventInput = {
  where: Prisma.WorldEventDeltaScalarWhereInput
  data: Prisma.XOR<Prisma.WorldEventDeltaUpdateManyMutationInput, Prisma.WorldEventDeltaUncheckedUpdateManyWithoutWorldEventInput>
}

export type WorldEventDeltaScalarWhereInput = {
  AND?: Prisma.WorldEventDeltaScalarWhereInput | Prisma.WorldEventDeltaScalarWhereInput[]
  OR?: Prisma.WorldEventDeltaScalarWhereInput[]
  NOT?: Prisma.WorldEventDeltaScalarWhereInput | Prisma.WorldEventDeltaScalarWhereInput[]
  id?: Prisma.StringFilter<"WorldEventDelta"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldEventDelta"> | Date | string
  timestamp?: Prisma.BigIntFilter<"WorldEventDelta"> | bigint | number
  name?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  description?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  descriptionRich?: Prisma.StringNullableFilter<"WorldEventDelta"> | string | null
  worldEventId?: Prisma.StringFilter<"WorldEventDelta"> | string
}

export type WorldEventDeltaCreateManyWorldEventInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  timestamp: bigint | number
  name?: string | null
  description?: string | null
  descriptionRich?: string | null
}

export type WorldEventDeltaUpdateWithoutWorldEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorldEventDeltaUncheckedUpdateWithoutWorldEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorldEventDeltaUncheckedUpdateManyWithoutWorldEventInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timestamp?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  descriptionRich?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type WorldEventDeltaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  timestamp?: boolean
  name?: boolean
  description?: boolean
  descriptionRich?: boolean
  worldEventId?: boolean
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventDelta"]>

export type WorldEventDeltaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  timestamp?: boolean
  name?: boolean
  description?: boolean
  descriptionRich?: boolean
  worldEventId?: boolean
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventDelta"]>

export type WorldEventDeltaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  timestamp?: boolean
  name?: boolean
  description?: boolean
  descriptionRich?: boolean
  worldEventId?: boolean
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldEventDelta"]>

export type WorldEventDeltaSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  timestamp?: boolean
  name?: boolean
  description?: boolean
  descriptionRich?: boolean
  worldEventId?: boolean
}

export type WorldEventDeltaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "timestamp" | "name" | "description" | "descriptionRich" | "worldEventId", ExtArgs["result"]["worldEventDelta"]>
export type WorldEventDeltaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}
export type WorldEventDeltaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}
export type WorldEventDeltaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worldEvent?: boolean | Prisma.WorldEventDefaultArgs<ExtArgs>
}

export type $WorldEventDeltaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorldEventDelta"
  objects: {
    worldEvent: Prisma.$WorldEventPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    timestamp: bigint
    name: string | null
    description: string | null
    descriptionRich: string | null
    worldEventId: string
  }, ExtArgs["result"]["worldEventDelta"]>
  composites: {}
}

export type WorldEventDeltaGetPayload<S extends boolean | null | undefined | WorldEventDeltaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload, S>

export type WorldEventDeltaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorldEventDeltaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorldEventDeltaCountAggregateInputType | true
  }

export interface WorldEventDeltaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorldEventDelta'], meta: { name: 'WorldEventDelta' } }
  /**
   * Find zero or one WorldEventDelta that matches the filter.
   * @param {WorldEventDeltaFindUniqueArgs} args - Arguments to find a WorldEventDelta
   * @example
   * // Get one WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorldEventDeltaFindUniqueArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorldEventDelta that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorldEventDeltaFindUniqueOrThrowArgs} args - Arguments to find a WorldEventDelta
   * @example
   * // Get one WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorldEventDeltaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldEventDelta that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaFindFirstArgs} args - Arguments to find a WorldEventDelta
   * @example
   * // Get one WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorldEventDeltaFindFirstArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldEventDelta that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaFindFirstOrThrowArgs} args - Arguments to find a WorldEventDelta
   * @example
   * // Get one WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorldEventDeltaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorldEventDeltas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorldEventDeltas
   * const worldEventDeltas = await prisma.worldEventDelta.findMany()
   * 
   * // Get first 10 WorldEventDeltas
   * const worldEventDeltas = await prisma.worldEventDelta.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const worldEventDeltaWithIdOnly = await prisma.worldEventDelta.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorldEventDeltaFindManyArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorldEventDelta.
   * @param {WorldEventDeltaCreateArgs} args - Arguments to create a WorldEventDelta.
   * @example
   * // Create one WorldEventDelta
   * const WorldEventDelta = await prisma.worldEventDelta.create({
   *   data: {
   *     // ... data to create a WorldEventDelta
   *   }
   * })
   * 
   */
  create<T extends WorldEventDeltaCreateArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaCreateArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorldEventDeltas.
   * @param {WorldEventDeltaCreateManyArgs} args - Arguments to create many WorldEventDeltas.
   * @example
   * // Create many WorldEventDeltas
   * const worldEventDelta = await prisma.worldEventDelta.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorldEventDeltaCreateManyArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorldEventDeltas and returns the data saved in the database.
   * @param {WorldEventDeltaCreateManyAndReturnArgs} args - Arguments to create many WorldEventDeltas.
   * @example
   * // Create many WorldEventDeltas
   * const worldEventDelta = await prisma.worldEventDelta.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorldEventDeltas and only return the `id`
   * const worldEventDeltaWithIdOnly = await prisma.worldEventDelta.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorldEventDeltaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorldEventDelta.
   * @param {WorldEventDeltaDeleteArgs} args - Arguments to delete one WorldEventDelta.
   * @example
   * // Delete one WorldEventDelta
   * const WorldEventDelta = await prisma.worldEventDelta.delete({
   *   where: {
   *     // ... filter to delete one WorldEventDelta
   *   }
   * })
   * 
   */
  delete<T extends WorldEventDeltaDeleteArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaDeleteArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorldEventDelta.
   * @param {WorldEventDeltaUpdateArgs} args - Arguments to update one WorldEventDelta.
   * @example
   * // Update one WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorldEventDeltaUpdateArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaUpdateArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorldEventDeltas.
   * @param {WorldEventDeltaDeleteManyArgs} args - Arguments to filter WorldEventDeltas to delete.
   * @example
   * // Delete a few WorldEventDeltas
   * const { count } = await prisma.worldEventDelta.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorldEventDeltaDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorldEventDeltaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldEventDeltas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorldEventDeltas
   * const worldEventDelta = await prisma.worldEventDelta.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorldEventDeltaUpdateManyArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldEventDeltas and returns the data updated in the database.
   * @param {WorldEventDeltaUpdateManyAndReturnArgs} args - Arguments to update many WorldEventDeltas.
   * @example
   * // Update many WorldEventDeltas
   * const worldEventDelta = await prisma.worldEventDelta.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorldEventDeltas and only return the `id`
   * const worldEventDeltaWithIdOnly = await prisma.worldEventDelta.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorldEventDeltaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorldEventDelta.
   * @param {WorldEventDeltaUpsertArgs} args - Arguments to update or create a WorldEventDelta.
   * @example
   * // Update or create a WorldEventDelta
   * const worldEventDelta = await prisma.worldEventDelta.upsert({
   *   create: {
   *     // ... data to create a WorldEventDelta
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorldEventDelta we want to update
   *   }
   * })
   */
  upsert<T extends WorldEventDeltaUpsertArgs>(args: Prisma.SelectSubset<T, WorldEventDeltaUpsertArgs<ExtArgs>>): Prisma.Prisma__WorldEventDeltaClient<runtime.Types.Result.GetResult<Prisma.$WorldEventDeltaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorldEventDeltas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaCountArgs} args - Arguments to filter WorldEventDeltas to count.
   * @example
   * // Count the number of WorldEventDeltas
   * const count = await prisma.worldEventDelta.count({
   *   where: {
   *     // ... the filter for the WorldEventDeltas we want to count
   *   }
   * })
  **/
  count<T extends WorldEventDeltaCountArgs>(
    args?: Prisma.Subset<T, WorldEventDeltaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorldEventDeltaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorldEventDelta.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorldEventDeltaAggregateArgs>(args: Prisma.Subset<T, WorldEventDeltaAggregateArgs>): Prisma.PrismaPromise<GetWorldEventDeltaAggregateType<T>>

  /**
   * Group by WorldEventDelta.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldEventDeltaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorldEventDeltaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorldEventDeltaGroupByArgs['orderBy'] }
      : { orderBy?: WorldEventDeltaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorldEventDeltaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorldEventDeltaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorldEventDelta model
 */
readonly fields: WorldEventDeltaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorldEventDelta.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorldEventDeltaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  worldEvent<T extends Prisma.WorldEventDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorldEventDefaultArgs<ExtArgs>>): Prisma.Prisma__WorldEventClient<runtime.Types.Result.GetResult<Prisma.$WorldEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorldEventDelta model
 */
export interface WorldEventDeltaFieldRefs {
  readonly id: Prisma.FieldRef<"WorldEventDelta", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorldEventDelta", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorldEventDelta", 'DateTime'>
  readonly timestamp: Prisma.FieldRef<"WorldEventDelta", 'BigInt'>
  readonly name: Prisma.FieldRef<"WorldEventDelta", 'String'>
  readonly description: Prisma.FieldRef<"WorldEventDelta", 'String'>
  readonly descriptionRich: Prisma.FieldRef<"WorldEventDelta", 'String'>
  readonly worldEventId: Prisma.FieldRef<"WorldEventDelta", 'String'>
}
    

// Custom InputTypes
/**
 * WorldEventDelta findUnique
 */
export type WorldEventDeltaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventDelta to fetch.
   */
  where: Prisma.WorldEventDeltaWhereUniqueInput
}

/**
 * WorldEventDelta findUniqueOrThrow
 */
export type WorldEventDeltaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventDelta to fetch.
   */
  where: Prisma.WorldEventDeltaWhereUniqueInput
}

/**
 * WorldEventDelta findFirst
 */
export type WorldEventDeltaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventDelta to fetch.
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventDeltas to fetch.
   */
  orderBy?: Prisma.WorldEventDeltaOrderByWithRelationInput | Prisma.WorldEventDeltaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldEventDeltas.
   */
  cursor?: Prisma.WorldEventDeltaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventDeltas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventDeltas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldEventDeltas.
   */
  distinct?: Prisma.WorldEventDeltaScalarFieldEnum | Prisma.WorldEventDeltaScalarFieldEnum[]
}

/**
 * WorldEventDelta findFirstOrThrow
 */
export type WorldEventDeltaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventDelta to fetch.
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventDeltas to fetch.
   */
  orderBy?: Prisma.WorldEventDeltaOrderByWithRelationInput | Prisma.WorldEventDeltaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldEventDeltas.
   */
  cursor?: Prisma.WorldEventDeltaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventDeltas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventDeltas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldEventDeltas.
   */
  distinct?: Prisma.WorldEventDeltaScalarFieldEnum | Prisma.WorldEventDeltaScalarFieldEnum[]
}

/**
 * WorldEventDelta findMany
 */
export type WorldEventDeltaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter, which WorldEventDeltas to fetch.
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldEventDeltas to fetch.
   */
  orderBy?: Prisma.WorldEventDeltaOrderByWithRelationInput | Prisma.WorldEventDeltaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorldEventDeltas.
   */
  cursor?: Prisma.WorldEventDeltaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldEventDeltas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldEventDeltas.
   */
  skip?: number
  distinct?: Prisma.WorldEventDeltaScalarFieldEnum | Prisma.WorldEventDeltaScalarFieldEnum[]
}

/**
 * WorldEventDelta create
 */
export type WorldEventDeltaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * The data needed to create a WorldEventDelta.
   */
  data: Prisma.XOR<Prisma.WorldEventDeltaCreateInput, Prisma.WorldEventDeltaUncheckedCreateInput>
}

/**
 * WorldEventDelta createMany
 */
export type WorldEventDeltaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorldEventDeltas.
   */
  data: Prisma.WorldEventDeltaCreateManyInput | Prisma.WorldEventDeltaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorldEventDelta createManyAndReturn
 */
export type WorldEventDeltaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * The data used to create many WorldEventDeltas.
   */
  data: Prisma.WorldEventDeltaCreateManyInput | Prisma.WorldEventDeltaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorldEventDelta update
 */
export type WorldEventDeltaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * The data needed to update a WorldEventDelta.
   */
  data: Prisma.XOR<Prisma.WorldEventDeltaUpdateInput, Prisma.WorldEventDeltaUncheckedUpdateInput>
  /**
   * Choose, which WorldEventDelta to update.
   */
  where: Prisma.WorldEventDeltaWhereUniqueInput
}

/**
 * WorldEventDelta updateMany
 */
export type WorldEventDeltaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorldEventDeltas.
   */
  data: Prisma.XOR<Prisma.WorldEventDeltaUpdateManyMutationInput, Prisma.WorldEventDeltaUncheckedUpdateManyInput>
  /**
   * Filter which WorldEventDeltas to update
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * Limit how many WorldEventDeltas to update.
   */
  limit?: number
}

/**
 * WorldEventDelta updateManyAndReturn
 */
export type WorldEventDeltaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * The data used to update WorldEventDeltas.
   */
  data: Prisma.XOR<Prisma.WorldEventDeltaUpdateManyMutationInput, Prisma.WorldEventDeltaUncheckedUpdateManyInput>
  /**
   * Filter which WorldEventDeltas to update
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * Limit how many WorldEventDeltas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorldEventDelta upsert
 */
export type WorldEventDeltaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * The filter to search for the WorldEventDelta to update in case it exists.
   */
  where: Prisma.WorldEventDeltaWhereUniqueInput
  /**
   * In case the WorldEventDelta found by the `where` argument doesn't exist, create a new WorldEventDelta with this data.
   */
  create: Prisma.XOR<Prisma.WorldEventDeltaCreateInput, Prisma.WorldEventDeltaUncheckedCreateInput>
  /**
   * In case the WorldEventDelta was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorldEventDeltaUpdateInput, Prisma.WorldEventDeltaUncheckedUpdateInput>
}

/**
 * WorldEventDelta delete
 */
export type WorldEventDeltaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
  /**
   * Filter which WorldEventDelta to delete.
   */
  where: Prisma.WorldEventDeltaWhereUniqueInput
}

/**
 * WorldEventDelta deleteMany
 */
export type WorldEventDeltaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldEventDeltas to delete
   */
  where?: Prisma.WorldEventDeltaWhereInput
  /**
   * Limit how many WorldEventDeltas to delete.
   */
  limit?: number
}

/**
 * WorldEventDelta without action
 */
export type WorldEventDeltaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldEventDelta
   */
  select?: Prisma.WorldEventDeltaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldEventDelta
   */
  omit?: Prisma.WorldEventDeltaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldEventDeltaInclude<ExtArgs> | null
}
