
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorldShareLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorldShareLink
 * 
 */
export type WorldShareLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$WorldShareLinkPayload>

export type AggregateWorldShareLink = {
  _count: WorldShareLinkCountAggregateOutputType | null
  _avg: WorldShareLinkAvgAggregateOutputType | null
  _sum: WorldShareLinkSumAggregateOutputType | null
  _min: WorldShareLinkMinAggregateOutputType | null
  _max: WorldShareLinkMaxAggregateOutputType | null
}

export type WorldShareLinkAvgAggregateOutputType = {
  usageCount: number | null
}

export type WorldShareLinkSumAggregateOutputType = {
  usageCount: number | null
}

export type WorldShareLinkMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  slug: string | null
  label: string | null
  expiresAt: Date | null
  accessMode: $Enums.CollaboratorAccess | null
  usageCount: number | null
  worldId: string | null
}

export type WorldShareLinkMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  slug: string | null
  label: string | null
  expiresAt: Date | null
  accessMode: $Enums.CollaboratorAccess | null
  usageCount: number | null
  worldId: string | null
}

export type WorldShareLinkCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  slug: number
  label: number
  expiresAt: number
  accessMode: number
  usageCount: number
  worldId: number
  _all: number
}


export type WorldShareLinkAvgAggregateInputType = {
  usageCount?: true
}

export type WorldShareLinkSumAggregateInputType = {
  usageCount?: true
}

export type WorldShareLinkMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  label?: true
  expiresAt?: true
  accessMode?: true
  usageCount?: true
  worldId?: true
}

export type WorldShareLinkMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  label?: true
  expiresAt?: true
  accessMode?: true
  usageCount?: true
  worldId?: true
}

export type WorldShareLinkCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  slug?: true
  label?: true
  expiresAt?: true
  accessMode?: true
  usageCount?: true
  worldId?: true
  _all?: true
}

export type WorldShareLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldShareLink to aggregate.
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldShareLinks to fetch.
   */
  orderBy?: Prisma.WorldShareLinkOrderByWithRelationInput | Prisma.WorldShareLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorldShareLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldShareLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldShareLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorldShareLinks
  **/
  _count?: true | WorldShareLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorldShareLinkAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorldShareLinkSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorldShareLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorldShareLinkMaxAggregateInputType
}

export type GetWorldShareLinkAggregateType<T extends WorldShareLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateWorldShareLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorldShareLink[P]>
    : Prisma.GetScalarType<T[P], AggregateWorldShareLink[P]>
}




export type WorldShareLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorldShareLinkWhereInput
  orderBy?: Prisma.WorldShareLinkOrderByWithAggregationInput | Prisma.WorldShareLinkOrderByWithAggregationInput[]
  by: Prisma.WorldShareLinkScalarFieldEnum[] | Prisma.WorldShareLinkScalarFieldEnum
  having?: Prisma.WorldShareLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorldShareLinkCountAggregateInputType | true
  _avg?: WorldShareLinkAvgAggregateInputType
  _sum?: WorldShareLinkSumAggregateInputType
  _min?: WorldShareLinkMinAggregateInputType
  _max?: WorldShareLinkMaxAggregateInputType
}

export type WorldShareLinkGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  slug: string
  label: string | null
  expiresAt: Date | null
  accessMode: $Enums.CollaboratorAccess
  usageCount: number
  worldId: string
  _count: WorldShareLinkCountAggregateOutputType | null
  _avg: WorldShareLinkAvgAggregateOutputType | null
  _sum: WorldShareLinkSumAggregateOutputType | null
  _min: WorldShareLinkMinAggregateOutputType | null
  _max: WorldShareLinkMaxAggregateOutputType | null
}

type GetWorldShareLinkGroupByPayload<T extends WorldShareLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorldShareLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorldShareLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorldShareLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorldShareLinkGroupByOutputType[P]>
      }
    >
  >



export type WorldShareLinkWhereInput = {
  AND?: Prisma.WorldShareLinkWhereInput | Prisma.WorldShareLinkWhereInput[]
  OR?: Prisma.WorldShareLinkWhereInput[]
  NOT?: Prisma.WorldShareLinkWhereInput | Prisma.WorldShareLinkWhereInput[]
  id?: Prisma.StringFilter<"WorldShareLink"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  slug?: Prisma.StringFilter<"WorldShareLink"> | string
  label?: Prisma.StringNullableFilter<"WorldShareLink"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"WorldShareLink"> | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFilter<"WorldShareLink"> | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFilter<"WorldShareLink"> | number
  worldId?: Prisma.StringFilter<"WorldShareLink"> | string
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}

export type WorldShareLinkOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  accessMode?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  world?: Prisma.WorldOrderByWithRelationInput
}

export type WorldShareLinkWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.WorldShareLinkWhereInput | Prisma.WorldShareLinkWhereInput[]
  OR?: Prisma.WorldShareLinkWhereInput[]
  NOT?: Prisma.WorldShareLinkWhereInput | Prisma.WorldShareLinkWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  label?: Prisma.StringNullableFilter<"WorldShareLink"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"WorldShareLink"> | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFilter<"WorldShareLink"> | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFilter<"WorldShareLink"> | number
  worldId?: Prisma.StringFilter<"WorldShareLink"> | string
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}, "id" | "id" | "slug">

export type WorldShareLinkOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  accessMode?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  _count?: Prisma.WorldShareLinkCountOrderByAggregateInput
  _avg?: Prisma.WorldShareLinkAvgOrderByAggregateInput
  _max?: Prisma.WorldShareLinkMaxOrderByAggregateInput
  _min?: Prisma.WorldShareLinkMinOrderByAggregateInput
  _sum?: Prisma.WorldShareLinkSumOrderByAggregateInput
}

export type WorldShareLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorldShareLinkScalarWhereWithAggregatesInput | Prisma.WorldShareLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorldShareLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorldShareLinkScalarWhereWithAggregatesInput | Prisma.WorldShareLinkScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorldShareLink"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorldShareLink"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"WorldShareLink"> | Date | string
  slug?: Prisma.StringWithAggregatesFilter<"WorldShareLink"> | string
  label?: Prisma.StringNullableWithAggregatesFilter<"WorldShareLink"> | string | null
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"WorldShareLink"> | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessWithAggregatesFilter<"WorldShareLink"> | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntWithAggregatesFilter<"WorldShareLink"> | number
  worldId?: Prisma.StringWithAggregatesFilter<"WorldShareLink"> | string
}

export type WorldShareLinkCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
  world: Prisma.WorldCreateNestedOneWithoutShareLinksInput
}

export type WorldShareLinkUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
  worldId: string
}

export type WorldShareLinkUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  world?: Prisma.WorldUpdateOneRequiredWithoutShareLinksNestedInput
}

export type WorldShareLinkUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldShareLinkCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
  worldId: string
}

export type WorldShareLinkUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WorldShareLinkUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WorldShareLinkListRelationFilter = {
  every?: Prisma.WorldShareLinkWhereInput
  some?: Prisma.WorldShareLinkWhereInput
  none?: Prisma.WorldShareLinkWhereInput
}

export type WorldShareLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorldShareLinkCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  label?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  accessMode?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldShareLinkAvgOrderByAggregateInput = {
  usageCount?: Prisma.SortOrder
}

export type WorldShareLinkMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  label?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  accessMode?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldShareLinkMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  label?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  accessMode?: Prisma.SortOrder
  usageCount?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type WorldShareLinkSumOrderByAggregateInput = {
  usageCount?: Prisma.SortOrder
}

export type WorldShareLinkCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput> | Prisma.WorldShareLinkCreateWithoutWorldInput[] | Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput | Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.WorldShareLinkCreateManyWorldInputEnvelope
  connect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
}

export type WorldShareLinkUncheckedCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput> | Prisma.WorldShareLinkCreateWithoutWorldInput[] | Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput | Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.WorldShareLinkCreateManyWorldInputEnvelope
  connect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
}

export type WorldShareLinkUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput> | Prisma.WorldShareLinkCreateWithoutWorldInput[] | Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput | Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.WorldShareLinkUpsertWithWhereUniqueWithoutWorldInput | Prisma.WorldShareLinkUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.WorldShareLinkCreateManyWorldInputEnvelope
  set?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  disconnect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  delete?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  connect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  update?: Prisma.WorldShareLinkUpdateWithWhereUniqueWithoutWorldInput | Prisma.WorldShareLinkUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.WorldShareLinkUpdateManyWithWhereWithoutWorldInput | Prisma.WorldShareLinkUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.WorldShareLinkScalarWhereInput | Prisma.WorldShareLinkScalarWhereInput[]
}

export type WorldShareLinkUncheckedUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput> | Prisma.WorldShareLinkCreateWithoutWorldInput[] | Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput | Prisma.WorldShareLinkCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.WorldShareLinkUpsertWithWhereUniqueWithoutWorldInput | Prisma.WorldShareLinkUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.WorldShareLinkCreateManyWorldInputEnvelope
  set?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  disconnect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  delete?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  connect?: Prisma.WorldShareLinkWhereUniqueInput | Prisma.WorldShareLinkWhereUniqueInput[]
  update?: Prisma.WorldShareLinkUpdateWithWhereUniqueWithoutWorldInput | Prisma.WorldShareLinkUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.WorldShareLinkUpdateManyWithWhereWithoutWorldInput | Prisma.WorldShareLinkUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.WorldShareLinkScalarWhereInput | Prisma.WorldShareLinkScalarWhereInput[]
}

export type WorldShareLinkCreateWithoutWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
}

export type WorldShareLinkUncheckedCreateWithoutWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
}

export type WorldShareLinkCreateOrConnectWithoutWorldInput = {
  where: Prisma.WorldShareLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput>
}

export type WorldShareLinkCreateManyWorldInputEnvelope = {
  data: Prisma.WorldShareLinkCreateManyWorldInput | Prisma.WorldShareLinkCreateManyWorldInput[]
  skipDuplicates?: boolean
}

export type WorldShareLinkUpsertWithWhereUniqueWithoutWorldInput = {
  where: Prisma.WorldShareLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.WorldShareLinkUpdateWithoutWorldInput, Prisma.WorldShareLinkUncheckedUpdateWithoutWorldInput>
  create: Prisma.XOR<Prisma.WorldShareLinkCreateWithoutWorldInput, Prisma.WorldShareLinkUncheckedCreateWithoutWorldInput>
}

export type WorldShareLinkUpdateWithWhereUniqueWithoutWorldInput = {
  where: Prisma.WorldShareLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.WorldShareLinkUpdateWithoutWorldInput, Prisma.WorldShareLinkUncheckedUpdateWithoutWorldInput>
}

export type WorldShareLinkUpdateManyWithWhereWithoutWorldInput = {
  where: Prisma.WorldShareLinkScalarWhereInput
  data: Prisma.XOR<Prisma.WorldShareLinkUpdateManyMutationInput, Prisma.WorldShareLinkUncheckedUpdateManyWithoutWorldInput>
}

export type WorldShareLinkScalarWhereInput = {
  AND?: Prisma.WorldShareLinkScalarWhereInput | Prisma.WorldShareLinkScalarWhereInput[]
  OR?: Prisma.WorldShareLinkScalarWhereInput[]
  NOT?: Prisma.WorldShareLinkScalarWhereInput | Prisma.WorldShareLinkScalarWhereInput[]
  id?: Prisma.StringFilter<"WorldShareLink"> | string
  createdAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"WorldShareLink"> | Date | string
  slug?: Prisma.StringFilter<"WorldShareLink"> | string
  label?: Prisma.StringNullableFilter<"WorldShareLink"> | string | null
  expiresAt?: Prisma.DateTimeNullableFilter<"WorldShareLink"> | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFilter<"WorldShareLink"> | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFilter<"WorldShareLink"> | number
  worldId?: Prisma.StringFilter<"WorldShareLink"> | string
}

export type WorldShareLinkCreateManyWorldInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  slug: string
  label?: string | null
  expiresAt?: Date | string | null
  accessMode: $Enums.CollaboratorAccess
  usageCount?: number
}

export type WorldShareLinkUpdateWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WorldShareLinkUncheckedUpdateWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type WorldShareLinkUncheckedUpdateManyWithoutWorldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessMode?: Prisma.EnumCollaboratorAccessFieldUpdateOperationsInput | $Enums.CollaboratorAccess
  usageCount?: Prisma.IntFieldUpdateOperationsInput | number
}



export type WorldShareLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  label?: boolean
  expiresAt?: boolean
  accessMode?: boolean
  usageCount?: boolean
  worldId?: boolean
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldShareLink"]>

export type WorldShareLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  label?: boolean
  expiresAt?: boolean
  accessMode?: boolean
  usageCount?: boolean
  worldId?: boolean
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldShareLink"]>

export type WorldShareLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  label?: boolean
  expiresAt?: boolean
  accessMode?: boolean
  usageCount?: boolean
  worldId?: boolean
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["worldShareLink"]>

export type WorldShareLinkSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  slug?: boolean
  label?: boolean
  expiresAt?: boolean
  accessMode?: boolean
  usageCount?: boolean
  worldId?: boolean
}

export type WorldShareLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "slug" | "label" | "expiresAt" | "accessMode" | "usageCount" | "worldId", ExtArgs["result"]["worldShareLink"]>
export type WorldShareLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}
export type WorldShareLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}
export type WorldShareLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}

export type $WorldShareLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorldShareLink"
  objects: {
    world: Prisma.$WorldPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    slug: string
    label: string | null
    expiresAt: Date | null
    accessMode: $Enums.CollaboratorAccess
    usageCount: number
    worldId: string
  }, ExtArgs["result"]["worldShareLink"]>
  composites: {}
}

export type WorldShareLinkGetPayload<S extends boolean | null | undefined | WorldShareLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload, S>

export type WorldShareLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorldShareLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorldShareLinkCountAggregateInputType | true
  }

export interface WorldShareLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorldShareLink'], meta: { name: 'WorldShareLink' } }
  /**
   * Find zero or one WorldShareLink that matches the filter.
   * @param {WorldShareLinkFindUniqueArgs} args - Arguments to find a WorldShareLink
   * @example
   * // Get one WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorldShareLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, WorldShareLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorldShareLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorldShareLinkFindUniqueOrThrowArgs} args - Arguments to find a WorldShareLink
   * @example
   * // Get one WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorldShareLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorldShareLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldShareLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkFindFirstArgs} args - Arguments to find a WorldShareLink
   * @example
   * // Get one WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorldShareLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorldShareLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkFindFirstOrThrowArgs} args - Arguments to find a WorldShareLink
   * @example
   * // Get one WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorldShareLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorldShareLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorldShareLinks
   * const worldShareLinks = await prisma.worldShareLink.findMany()
   * 
   * // Get first 10 WorldShareLinks
   * const worldShareLinks = await prisma.worldShareLink.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const worldShareLinkWithIdOnly = await prisma.worldShareLink.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorldShareLinkFindManyArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorldShareLink.
   * @param {WorldShareLinkCreateArgs} args - Arguments to create a WorldShareLink.
   * @example
   * // Create one WorldShareLink
   * const WorldShareLink = await prisma.worldShareLink.create({
   *   data: {
   *     // ... data to create a WorldShareLink
   *   }
   * })
   * 
   */
  create<T extends WorldShareLinkCreateArgs>(args: Prisma.SelectSubset<T, WorldShareLinkCreateArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorldShareLinks.
   * @param {WorldShareLinkCreateManyArgs} args - Arguments to create many WorldShareLinks.
   * @example
   * // Create many WorldShareLinks
   * const worldShareLink = await prisma.worldShareLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorldShareLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorldShareLinks and returns the data saved in the database.
   * @param {WorldShareLinkCreateManyAndReturnArgs} args - Arguments to create many WorldShareLinks.
   * @example
   * // Create many WorldShareLinks
   * const worldShareLink = await prisma.worldShareLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorldShareLinks and only return the `id`
   * const worldShareLinkWithIdOnly = await prisma.worldShareLink.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorldShareLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorldShareLink.
   * @param {WorldShareLinkDeleteArgs} args - Arguments to delete one WorldShareLink.
   * @example
   * // Delete one WorldShareLink
   * const WorldShareLink = await prisma.worldShareLink.delete({
   *   where: {
   *     // ... filter to delete one WorldShareLink
   *   }
   * })
   * 
   */
  delete<T extends WorldShareLinkDeleteArgs>(args: Prisma.SelectSubset<T, WorldShareLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorldShareLink.
   * @param {WorldShareLinkUpdateArgs} args - Arguments to update one WorldShareLink.
   * @example
   * // Update one WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorldShareLinkUpdateArgs>(args: Prisma.SelectSubset<T, WorldShareLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorldShareLinks.
   * @param {WorldShareLinkDeleteManyArgs} args - Arguments to filter WorldShareLinks to delete.
   * @example
   * // Delete a few WorldShareLinks
   * const { count } = await prisma.worldShareLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorldShareLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorldShareLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldShareLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorldShareLinks
   * const worldShareLink = await prisma.worldShareLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorldShareLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, WorldShareLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorldShareLinks and returns the data updated in the database.
   * @param {WorldShareLinkUpdateManyAndReturnArgs} args - Arguments to update many WorldShareLinks.
   * @example
   * // Update many WorldShareLinks
   * const worldShareLink = await prisma.worldShareLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorldShareLinks and only return the `id`
   * const worldShareLinkWithIdOnly = await prisma.worldShareLink.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorldShareLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorldShareLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorldShareLink.
   * @param {WorldShareLinkUpsertArgs} args - Arguments to update or create a WorldShareLink.
   * @example
   * // Update or create a WorldShareLink
   * const worldShareLink = await prisma.worldShareLink.upsert({
   *   create: {
   *     // ... data to create a WorldShareLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorldShareLink we want to update
   *   }
   * })
   */
  upsert<T extends WorldShareLinkUpsertArgs>(args: Prisma.SelectSubset<T, WorldShareLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__WorldShareLinkClient<runtime.Types.Result.GetResult<Prisma.$WorldShareLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorldShareLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkCountArgs} args - Arguments to filter WorldShareLinks to count.
   * @example
   * // Count the number of WorldShareLinks
   * const count = await prisma.worldShareLink.count({
   *   where: {
   *     // ... the filter for the WorldShareLinks we want to count
   *   }
   * })
  **/
  count<T extends WorldShareLinkCountArgs>(
    args?: Prisma.Subset<T, WorldShareLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorldShareLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorldShareLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorldShareLinkAggregateArgs>(args: Prisma.Subset<T, WorldShareLinkAggregateArgs>): Prisma.PrismaPromise<GetWorldShareLinkAggregateType<T>>

  /**
   * Group by WorldShareLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorldShareLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorldShareLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorldShareLinkGroupByArgs['orderBy'] }
      : { orderBy?: WorldShareLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorldShareLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorldShareLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorldShareLink model
 */
readonly fields: WorldShareLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorldShareLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorldShareLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  world<T extends Prisma.WorldDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorldDefaultArgs<ExtArgs>>): Prisma.Prisma__WorldClient<runtime.Types.Result.GetResult<Prisma.$WorldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorldShareLink model
 */
export interface WorldShareLinkFieldRefs {
  readonly id: Prisma.FieldRef<"WorldShareLink", 'String'>
  readonly createdAt: Prisma.FieldRef<"WorldShareLink", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"WorldShareLink", 'DateTime'>
  readonly slug: Prisma.FieldRef<"WorldShareLink", 'String'>
  readonly label: Prisma.FieldRef<"WorldShareLink", 'String'>
  readonly expiresAt: Prisma.FieldRef<"WorldShareLink", 'DateTime'>
  readonly accessMode: Prisma.FieldRef<"WorldShareLink", 'CollaboratorAccess'>
  readonly usageCount: Prisma.FieldRef<"WorldShareLink", 'Int'>
  readonly worldId: Prisma.FieldRef<"WorldShareLink", 'String'>
}
    

// Custom InputTypes
/**
 * WorldShareLink findUnique
 */
export type WorldShareLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter, which WorldShareLink to fetch.
   */
  where: Prisma.WorldShareLinkWhereUniqueInput
}

/**
 * WorldShareLink findUniqueOrThrow
 */
export type WorldShareLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter, which WorldShareLink to fetch.
   */
  where: Prisma.WorldShareLinkWhereUniqueInput
}

/**
 * WorldShareLink findFirst
 */
export type WorldShareLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter, which WorldShareLink to fetch.
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldShareLinks to fetch.
   */
  orderBy?: Prisma.WorldShareLinkOrderByWithRelationInput | Prisma.WorldShareLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldShareLinks.
   */
  cursor?: Prisma.WorldShareLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldShareLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldShareLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldShareLinks.
   */
  distinct?: Prisma.WorldShareLinkScalarFieldEnum | Prisma.WorldShareLinkScalarFieldEnum[]
}

/**
 * WorldShareLink findFirstOrThrow
 */
export type WorldShareLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter, which WorldShareLink to fetch.
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldShareLinks to fetch.
   */
  orderBy?: Prisma.WorldShareLinkOrderByWithRelationInput | Prisma.WorldShareLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorldShareLinks.
   */
  cursor?: Prisma.WorldShareLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldShareLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldShareLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorldShareLinks.
   */
  distinct?: Prisma.WorldShareLinkScalarFieldEnum | Prisma.WorldShareLinkScalarFieldEnum[]
}

/**
 * WorldShareLink findMany
 */
export type WorldShareLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter, which WorldShareLinks to fetch.
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorldShareLinks to fetch.
   */
  orderBy?: Prisma.WorldShareLinkOrderByWithRelationInput | Prisma.WorldShareLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorldShareLinks.
   */
  cursor?: Prisma.WorldShareLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorldShareLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorldShareLinks.
   */
  skip?: number
  distinct?: Prisma.WorldShareLinkScalarFieldEnum | Prisma.WorldShareLinkScalarFieldEnum[]
}

/**
 * WorldShareLink create
 */
export type WorldShareLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a WorldShareLink.
   */
  data: Prisma.XOR<Prisma.WorldShareLinkCreateInput, Prisma.WorldShareLinkUncheckedCreateInput>
}

/**
 * WorldShareLink createMany
 */
export type WorldShareLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorldShareLinks.
   */
  data: Prisma.WorldShareLinkCreateManyInput | Prisma.WorldShareLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorldShareLink createManyAndReturn
 */
export type WorldShareLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * The data used to create many WorldShareLinks.
   */
  data: Prisma.WorldShareLinkCreateManyInput | Prisma.WorldShareLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorldShareLink update
 */
export type WorldShareLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a WorldShareLink.
   */
  data: Prisma.XOR<Prisma.WorldShareLinkUpdateInput, Prisma.WorldShareLinkUncheckedUpdateInput>
  /**
   * Choose, which WorldShareLink to update.
   */
  where: Prisma.WorldShareLinkWhereUniqueInput
}

/**
 * WorldShareLink updateMany
 */
export type WorldShareLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorldShareLinks.
   */
  data: Prisma.XOR<Prisma.WorldShareLinkUpdateManyMutationInput, Prisma.WorldShareLinkUncheckedUpdateManyInput>
  /**
   * Filter which WorldShareLinks to update
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * Limit how many WorldShareLinks to update.
   */
  limit?: number
}

/**
 * WorldShareLink updateManyAndReturn
 */
export type WorldShareLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * The data used to update WorldShareLinks.
   */
  data: Prisma.XOR<Prisma.WorldShareLinkUpdateManyMutationInput, Prisma.WorldShareLinkUncheckedUpdateManyInput>
  /**
   * Filter which WorldShareLinks to update
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * Limit how many WorldShareLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorldShareLink upsert
 */
export type WorldShareLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the WorldShareLink to update in case it exists.
   */
  where: Prisma.WorldShareLinkWhereUniqueInput
  /**
   * In case the WorldShareLink found by the `where` argument doesn't exist, create a new WorldShareLink with this data.
   */
  create: Prisma.XOR<Prisma.WorldShareLinkCreateInput, Prisma.WorldShareLinkUncheckedCreateInput>
  /**
   * In case the WorldShareLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorldShareLinkUpdateInput, Prisma.WorldShareLinkUncheckedUpdateInput>
}

/**
 * WorldShareLink delete
 */
export type WorldShareLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
  /**
   * Filter which WorldShareLink to delete.
   */
  where: Prisma.WorldShareLinkWhereUniqueInput
}

/**
 * WorldShareLink deleteMany
 */
export type WorldShareLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorldShareLinks to delete
   */
  where?: Prisma.WorldShareLinkWhereInput
  /**
   * Limit how many WorldShareLinks to delete.
   */
  limit?: number
}

/**
 * WorldShareLink without action
 */
export type WorldShareLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorldShareLink
   */
  select?: Prisma.WorldShareLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorldShareLink
   */
  omit?: Prisma.WorldShareLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorldShareLinkInclude<ExtArgs> | null
}
