
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Actor: 'Actor',
  UserAnnouncement: 'UserAnnouncement',
  Asset: 'Asset',
  Calendar: 'Calendar',
  CalendarUnit: 'CalendarUnit',
  CalendarUnitRelation: 'CalendarUnitRelation',
  SavedColor: 'SavedColor',
  Flags: 'Flags',
  UserFavoriteIconSet: 'UserFavoriteIconSet',
  WorldCommonIconSet: 'WorldCommonIconSet',
  Mention: 'Mention',
  MindmapNode: 'MindmapNode',
  User: 'User',
  CollaboratingUser: 'CollaboratingUser',
  Tag: 'Tag',
  WikiArticle: 'WikiArticle',
  World: 'World',
  WorldEvent: 'WorldEvent',
  WorldEventDelta: 'WorldEventDelta',
  WorldEventTrack: 'WorldEventTrack'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "actor" | "userAnnouncement" | "asset" | "calendar" | "calendarUnit" | "calendarUnitRelation" | "savedColor" | "flags" | "userFavoriteIconSet" | "worldCommonIconSet" | "mention" | "mindmapNode" | "user" | "collaboratingUser" | "tag" | "wikiArticle" | "world" | "worldEvent" | "worldEventDelta" | "worldEventTrack"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Actor: {
      payload: Prisma.$ActorPayload<ExtArgs>
      fields: Prisma.ActorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ActorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ActorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        findFirst: {
          args: Prisma.ActorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ActorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        findMany: {
          args: Prisma.ActorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>[]
        }
        create: {
          args: Prisma.ActorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        createMany: {
          args: Prisma.ActorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ActorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>[]
        }
        delete: {
          args: Prisma.ActorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        update: {
          args: Prisma.ActorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        deleteMany: {
          args: Prisma.ActorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ActorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ActorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>[]
        }
        upsert: {
          args: Prisma.ActorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ActorPayload>
        }
        aggregate: {
          args: Prisma.ActorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateActor>
        }
        groupBy: {
          args: Prisma.ActorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ActorGroupByOutputType>[]
        }
        count: {
          args: Prisma.ActorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ActorCountAggregateOutputType> | number
        }
      }
    }
    UserAnnouncement: {
      payload: Prisma.$UserAnnouncementPayload<ExtArgs>
      fields: Prisma.UserAnnouncementFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserAnnouncementFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserAnnouncementFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        findFirst: {
          args: Prisma.UserAnnouncementFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserAnnouncementFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        findMany: {
          args: Prisma.UserAnnouncementFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>[]
        }
        create: {
          args: Prisma.UserAnnouncementCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        createMany: {
          args: Prisma.UserAnnouncementCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserAnnouncementCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>[]
        }
        delete: {
          args: Prisma.UserAnnouncementDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        update: {
          args: Prisma.UserAnnouncementUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        deleteMany: {
          args: Prisma.UserAnnouncementDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserAnnouncementUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserAnnouncementUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>[]
        }
        upsert: {
          args: Prisma.UserAnnouncementUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserAnnouncementPayload>
        }
        aggregate: {
          args: Prisma.UserAnnouncementAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserAnnouncement>
        }
        groupBy: {
          args: Prisma.UserAnnouncementGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAnnouncementGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserAnnouncementCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserAnnouncementCountAggregateOutputType> | number
        }
      }
    }
    Asset: {
      payload: Prisma.$AssetPayload<ExtArgs>
      fields: Prisma.AssetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AssetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AssetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        findFirst: {
          args: Prisma.AssetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AssetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        findMany: {
          args: Prisma.AssetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>[]
        }
        create: {
          args: Prisma.AssetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        createMany: {
          args: Prisma.AssetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AssetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>[]
        }
        delete: {
          args: Prisma.AssetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        update: {
          args: Prisma.AssetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        deleteMany: {
          args: Prisma.AssetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AssetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AssetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>[]
        }
        upsert: {
          args: Prisma.AssetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AssetPayload>
        }
        aggregate: {
          args: Prisma.AssetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAsset>
        }
        groupBy: {
          args: Prisma.AssetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssetGroupByOutputType>[]
        }
        count: {
          args: Prisma.AssetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AssetCountAggregateOutputType> | number
        }
      }
    }
    Calendar: {
      payload: Prisma.$CalendarPayload<ExtArgs>
      fields: Prisma.CalendarFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CalendarFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CalendarFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        findFirst: {
          args: Prisma.CalendarFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CalendarFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        findMany: {
          args: Prisma.CalendarFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>[]
        }
        create: {
          args: Prisma.CalendarCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        createMany: {
          args: Prisma.CalendarCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CalendarCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>[]
        }
        delete: {
          args: Prisma.CalendarDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        update: {
          args: Prisma.CalendarUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        deleteMany: {
          args: Prisma.CalendarDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CalendarUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CalendarUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>[]
        }
        upsert: {
          args: Prisma.CalendarUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarPayload>
        }
        aggregate: {
          args: Prisma.CalendarAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCalendar>
        }
        groupBy: {
          args: Prisma.CalendarGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarGroupByOutputType>[]
        }
        count: {
          args: Prisma.CalendarCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarCountAggregateOutputType> | number
        }
      }
    }
    CalendarUnit: {
      payload: Prisma.$CalendarUnitPayload<ExtArgs>
      fields: Prisma.CalendarUnitFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CalendarUnitFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CalendarUnitFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        findFirst: {
          args: Prisma.CalendarUnitFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CalendarUnitFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        findMany: {
          args: Prisma.CalendarUnitFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>[]
        }
        create: {
          args: Prisma.CalendarUnitCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        createMany: {
          args: Prisma.CalendarUnitCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CalendarUnitCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>[]
        }
        delete: {
          args: Prisma.CalendarUnitDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        update: {
          args: Prisma.CalendarUnitUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        deleteMany: {
          args: Prisma.CalendarUnitDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CalendarUnitUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CalendarUnitUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>[]
        }
        upsert: {
          args: Prisma.CalendarUnitUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitPayload>
        }
        aggregate: {
          args: Prisma.CalendarUnitAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCalendarUnit>
        }
        groupBy: {
          args: Prisma.CalendarUnitGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarUnitGroupByOutputType>[]
        }
        count: {
          args: Prisma.CalendarUnitCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarUnitCountAggregateOutputType> | number
        }
      }
    }
    CalendarUnitRelation: {
      payload: Prisma.$CalendarUnitRelationPayload<ExtArgs>
      fields: Prisma.CalendarUnitRelationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CalendarUnitRelationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CalendarUnitRelationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        findFirst: {
          args: Prisma.CalendarUnitRelationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CalendarUnitRelationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        findMany: {
          args: Prisma.CalendarUnitRelationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>[]
        }
        create: {
          args: Prisma.CalendarUnitRelationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        createMany: {
          args: Prisma.CalendarUnitRelationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CalendarUnitRelationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>[]
        }
        delete: {
          args: Prisma.CalendarUnitRelationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        update: {
          args: Prisma.CalendarUnitRelationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        deleteMany: {
          args: Prisma.CalendarUnitRelationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CalendarUnitRelationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CalendarUnitRelationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>[]
        }
        upsert: {
          args: Prisma.CalendarUnitRelationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CalendarUnitRelationPayload>
        }
        aggregate: {
          args: Prisma.CalendarUnitRelationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCalendarUnitRelation>
        }
        groupBy: {
          args: Prisma.CalendarUnitRelationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarUnitRelationGroupByOutputType>[]
        }
        count: {
          args: Prisma.CalendarUnitRelationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CalendarUnitRelationCountAggregateOutputType> | number
        }
      }
    }
    SavedColor: {
      payload: Prisma.$SavedColorPayload<ExtArgs>
      fields: Prisma.SavedColorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SavedColorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SavedColorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        findFirst: {
          args: Prisma.SavedColorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SavedColorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        findMany: {
          args: Prisma.SavedColorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>[]
        }
        create: {
          args: Prisma.SavedColorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        createMany: {
          args: Prisma.SavedColorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SavedColorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>[]
        }
        delete: {
          args: Prisma.SavedColorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        update: {
          args: Prisma.SavedColorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        deleteMany: {
          args: Prisma.SavedColorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SavedColorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SavedColorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>[]
        }
        upsert: {
          args: Prisma.SavedColorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SavedColorPayload>
        }
        aggregate: {
          args: Prisma.SavedColorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSavedColor>
        }
        groupBy: {
          args: Prisma.SavedColorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SavedColorGroupByOutputType>[]
        }
        count: {
          args: Prisma.SavedColorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SavedColorCountAggregateOutputType> | number
        }
      }
    }
    Flags: {
      payload: Prisma.$FlagsPayload<ExtArgs>
      fields: Prisma.FlagsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FlagsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FlagsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        findFirst: {
          args: Prisma.FlagsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FlagsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        findMany: {
          args: Prisma.FlagsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>[]
        }
        create: {
          args: Prisma.FlagsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        createMany: {
          args: Prisma.FlagsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FlagsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>[]
        }
        delete: {
          args: Prisma.FlagsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        update: {
          args: Prisma.FlagsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        deleteMany: {
          args: Prisma.FlagsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FlagsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FlagsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>[]
        }
        upsert: {
          args: Prisma.FlagsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FlagsPayload>
        }
        aggregate: {
          args: Prisma.FlagsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFlags>
        }
        groupBy: {
          args: Prisma.FlagsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FlagsGroupByOutputType>[]
        }
        count: {
          args: Prisma.FlagsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FlagsCountAggregateOutputType> | number
        }
      }
    }
    UserFavoriteIconSet: {
      payload: Prisma.$UserFavoriteIconSetPayload<ExtArgs>
      fields: Prisma.UserFavoriteIconSetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFavoriteIconSetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFavoriteIconSetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        findFirst: {
          args: Prisma.UserFavoriteIconSetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFavoriteIconSetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        findMany: {
          args: Prisma.UserFavoriteIconSetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>[]
        }
        create: {
          args: Prisma.UserFavoriteIconSetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        createMany: {
          args: Prisma.UserFavoriteIconSetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserFavoriteIconSetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>[]
        }
        delete: {
          args: Prisma.UserFavoriteIconSetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        update: {
          args: Prisma.UserFavoriteIconSetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        deleteMany: {
          args: Prisma.UserFavoriteIconSetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserFavoriteIconSetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserFavoriteIconSetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>[]
        }
        upsert: {
          args: Prisma.UserFavoriteIconSetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserFavoriteIconSetPayload>
        }
        aggregate: {
          args: Prisma.UserFavoriteIconSetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserFavoriteIconSet>
        }
        groupBy: {
          args: Prisma.UserFavoriteIconSetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserFavoriteIconSetGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserFavoriteIconSetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserFavoriteIconSetCountAggregateOutputType> | number
        }
      }
    }
    WorldCommonIconSet: {
      payload: Prisma.$WorldCommonIconSetPayload<ExtArgs>
      fields: Prisma.WorldCommonIconSetFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorldCommonIconSetFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorldCommonIconSetFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        findFirst: {
          args: Prisma.WorldCommonIconSetFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorldCommonIconSetFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        findMany: {
          args: Prisma.WorldCommonIconSetFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>[]
        }
        create: {
          args: Prisma.WorldCommonIconSetCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        createMany: {
          args: Prisma.WorldCommonIconSetCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorldCommonIconSetCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>[]
        }
        delete: {
          args: Prisma.WorldCommonIconSetDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        update: {
          args: Prisma.WorldCommonIconSetUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        deleteMany: {
          args: Prisma.WorldCommonIconSetDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorldCommonIconSetUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorldCommonIconSetUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>[]
        }
        upsert: {
          args: Prisma.WorldCommonIconSetUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldCommonIconSetPayload>
        }
        aggregate: {
          args: Prisma.WorldCommonIconSetAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorldCommonIconSet>
        }
        groupBy: {
          args: Prisma.WorldCommonIconSetGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldCommonIconSetGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorldCommonIconSetCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldCommonIconSetCountAggregateOutputType> | number
        }
      }
    }
    Mention: {
      payload: Prisma.$MentionPayload<ExtArgs>
      fields: Prisma.MentionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MentionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MentionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        findFirst: {
          args: Prisma.MentionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MentionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        findMany: {
          args: Prisma.MentionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>[]
        }
        create: {
          args: Prisma.MentionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        createMany: {
          args: Prisma.MentionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MentionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>[]
        }
        delete: {
          args: Prisma.MentionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        update: {
          args: Prisma.MentionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        deleteMany: {
          args: Prisma.MentionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MentionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MentionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>[]
        }
        upsert: {
          args: Prisma.MentionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MentionPayload>
        }
        aggregate: {
          args: Prisma.MentionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMention>
        }
        groupBy: {
          args: Prisma.MentionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MentionGroupByOutputType>[]
        }
        count: {
          args: Prisma.MentionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MentionCountAggregateOutputType> | number
        }
      }
    }
    MindmapNode: {
      payload: Prisma.$MindmapNodePayload<ExtArgs>
      fields: Prisma.MindmapNodeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MindmapNodeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MindmapNodeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        findFirst: {
          args: Prisma.MindmapNodeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MindmapNodeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        findMany: {
          args: Prisma.MindmapNodeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>[]
        }
        create: {
          args: Prisma.MindmapNodeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        createMany: {
          args: Prisma.MindmapNodeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MindmapNodeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>[]
        }
        delete: {
          args: Prisma.MindmapNodeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        update: {
          args: Prisma.MindmapNodeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        deleteMany: {
          args: Prisma.MindmapNodeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MindmapNodeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MindmapNodeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>[]
        }
        upsert: {
          args: Prisma.MindmapNodeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MindmapNodePayload>
        }
        aggregate: {
          args: Prisma.MindmapNodeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMindmapNode>
        }
        groupBy: {
          args: Prisma.MindmapNodeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MindmapNodeGroupByOutputType>[]
        }
        count: {
          args: Prisma.MindmapNodeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MindmapNodeCountAggregateOutputType> | number
        }
      }
    }
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    CollaboratingUser: {
      payload: Prisma.$CollaboratingUserPayload<ExtArgs>
      fields: Prisma.CollaboratingUserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CollaboratingUserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CollaboratingUserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        findFirst: {
          args: Prisma.CollaboratingUserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CollaboratingUserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        findMany: {
          args: Prisma.CollaboratingUserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>[]
        }
        create: {
          args: Prisma.CollaboratingUserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        createMany: {
          args: Prisma.CollaboratingUserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CollaboratingUserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>[]
        }
        delete: {
          args: Prisma.CollaboratingUserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        update: {
          args: Prisma.CollaboratingUserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        deleteMany: {
          args: Prisma.CollaboratingUserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CollaboratingUserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CollaboratingUserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>[]
        }
        upsert: {
          args: Prisma.CollaboratingUserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CollaboratingUserPayload>
        }
        aggregate: {
          args: Prisma.CollaboratingUserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCollaboratingUser>
        }
        groupBy: {
          args: Prisma.CollaboratingUserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CollaboratingUserGroupByOutputType>[]
        }
        count: {
          args: Prisma.CollaboratingUserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CollaboratingUserCountAggregateOutputType> | number
        }
      }
    }
    Tag: {
      payload: Prisma.$TagPayload<ExtArgs>
      fields: Prisma.TagFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TagFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TagFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        findFirst: {
          args: Prisma.TagFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TagFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        findMany: {
          args: Prisma.TagFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        create: {
          args: Prisma.TagCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        createMany: {
          args: Prisma.TagCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TagCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        delete: {
          args: Prisma.TagDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        update: {
          args: Prisma.TagUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        deleteMany: {
          args: Prisma.TagDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TagUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TagUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>[]
        }
        upsert: {
          args: Prisma.TagUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TagPayload>
        }
        aggregate: {
          args: Prisma.TagAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTag>
        }
        groupBy: {
          args: Prisma.TagGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TagGroupByOutputType>[]
        }
        count: {
          args: Prisma.TagCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TagCountAggregateOutputType> | number
        }
      }
    }
    WikiArticle: {
      payload: Prisma.$WikiArticlePayload<ExtArgs>
      fields: Prisma.WikiArticleFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WikiArticleFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WikiArticleFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        findFirst: {
          args: Prisma.WikiArticleFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WikiArticleFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        findMany: {
          args: Prisma.WikiArticleFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>[]
        }
        create: {
          args: Prisma.WikiArticleCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        createMany: {
          args: Prisma.WikiArticleCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WikiArticleCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>[]
        }
        delete: {
          args: Prisma.WikiArticleDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        update: {
          args: Prisma.WikiArticleUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        deleteMany: {
          args: Prisma.WikiArticleDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WikiArticleUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WikiArticleUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>[]
        }
        upsert: {
          args: Prisma.WikiArticleUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WikiArticlePayload>
        }
        aggregate: {
          args: Prisma.WikiArticleAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWikiArticle>
        }
        groupBy: {
          args: Prisma.WikiArticleGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiArticleGroupByOutputType>[]
        }
        count: {
          args: Prisma.WikiArticleCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WikiArticleCountAggregateOutputType> | number
        }
      }
    }
    World: {
      payload: Prisma.$WorldPayload<ExtArgs>
      fields: Prisma.WorldFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorldFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorldFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        findFirst: {
          args: Prisma.WorldFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorldFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        findMany: {
          args: Prisma.WorldFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>[]
        }
        create: {
          args: Prisma.WorldCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        createMany: {
          args: Prisma.WorldCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorldCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>[]
        }
        delete: {
          args: Prisma.WorldDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        update: {
          args: Prisma.WorldUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        deleteMany: {
          args: Prisma.WorldDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorldUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorldUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>[]
        }
        upsert: {
          args: Prisma.WorldUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldPayload>
        }
        aggregate: {
          args: Prisma.WorldAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorld>
        }
        groupBy: {
          args: Prisma.WorldGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorldCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldCountAggregateOutputType> | number
        }
      }
    }
    WorldEvent: {
      payload: Prisma.$WorldEventPayload<ExtArgs>
      fields: Prisma.WorldEventFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorldEventFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorldEventFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        findFirst: {
          args: Prisma.WorldEventFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorldEventFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        findMany: {
          args: Prisma.WorldEventFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>[]
        }
        create: {
          args: Prisma.WorldEventCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        createMany: {
          args: Prisma.WorldEventCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorldEventCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>[]
        }
        delete: {
          args: Prisma.WorldEventDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        update: {
          args: Prisma.WorldEventUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        deleteMany: {
          args: Prisma.WorldEventDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorldEventUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorldEventUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>[]
        }
        upsert: {
          args: Prisma.WorldEventUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventPayload>
        }
        aggregate: {
          args: Prisma.WorldEventAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorldEvent>
        }
        groupBy: {
          args: Prisma.WorldEventGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorldEventCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventCountAggregateOutputType> | number
        }
      }
    }
    WorldEventDelta: {
      payload: Prisma.$WorldEventDeltaPayload<ExtArgs>
      fields: Prisma.WorldEventDeltaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorldEventDeltaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorldEventDeltaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        findFirst: {
          args: Prisma.WorldEventDeltaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorldEventDeltaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        findMany: {
          args: Prisma.WorldEventDeltaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>[]
        }
        create: {
          args: Prisma.WorldEventDeltaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        createMany: {
          args: Prisma.WorldEventDeltaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorldEventDeltaCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>[]
        }
        delete: {
          args: Prisma.WorldEventDeltaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        update: {
          args: Prisma.WorldEventDeltaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        deleteMany: {
          args: Prisma.WorldEventDeltaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorldEventDeltaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorldEventDeltaUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>[]
        }
        upsert: {
          args: Prisma.WorldEventDeltaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventDeltaPayload>
        }
        aggregate: {
          args: Prisma.WorldEventDeltaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorldEventDelta>
        }
        groupBy: {
          args: Prisma.WorldEventDeltaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventDeltaGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorldEventDeltaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventDeltaCountAggregateOutputType> | number
        }
      }
    }
    WorldEventTrack: {
      payload: Prisma.$WorldEventTrackPayload<ExtArgs>
      fields: Prisma.WorldEventTrackFieldRefs
      operations: {
        findUnique: {
          args: Prisma.WorldEventTrackFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.WorldEventTrackFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        findFirst: {
          args: Prisma.WorldEventTrackFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.WorldEventTrackFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        findMany: {
          args: Prisma.WorldEventTrackFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>[]
        }
        create: {
          args: Prisma.WorldEventTrackCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        createMany: {
          args: Prisma.WorldEventTrackCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.WorldEventTrackCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>[]
        }
        delete: {
          args: Prisma.WorldEventTrackDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        update: {
          args: Prisma.WorldEventTrackUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        deleteMany: {
          args: Prisma.WorldEventTrackDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.WorldEventTrackUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.WorldEventTrackUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>[]
        }
        upsert: {
          args: Prisma.WorldEventTrackUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$WorldEventTrackPayload>
        }
        aggregate: {
          args: Prisma.WorldEventTrackAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorldEventTrack>
        }
        groupBy: {
          args: Prisma.WorldEventTrackGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventTrackGroupByOutputType>[]
        }
        count: {
          args: Prisma.WorldEventTrackCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorldEventTrackCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ActorScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  title: 'title',
  icon: 'icon',
  color: 'color',
  description: 'description',
  descriptionRich: 'descriptionRich',
  descriptionYjs: 'descriptionYjs',
  worldId: 'worldId'
} as const

export type ActorScalarFieldEnum = (typeof ActorScalarFieldEnum)[keyof typeof ActorScalarFieldEnum]


export const UserAnnouncementScalarFieldEnum = {
  id: 'id',
  timestamp: 'timestamp',
  isUnread: 'isUnread',
  type: 'type',
  title: 'title',
  description: 'description',
  userId: 'userId'
} as const

export type UserAnnouncementScalarFieldEnum = (typeof UserAnnouncementScalarFieldEnum)[keyof typeof UserAnnouncementScalarFieldEnum]


export const AssetScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  ownerId: 'ownerId',
  bucketKey: 'bucketKey',
  size: 'size',
  originalFileName: 'originalFileName',
  originalFileExtension: 'originalFileExtension',
  contentType: 'contentType',
  status: 'status'
} as const

export type AssetScalarFieldEnum = (typeof AssetScalarFieldEnum)[keyof typeof AssetScalarFieldEnum]


export const CalendarScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  position: 'position',
  originTime: 'originTime',
  name: 'name',
  dateFormat: 'dateFormat',
  worldId: 'worldId',
  ownerId: 'ownerId'
} as const

export type CalendarScalarFieldEnum = (typeof CalendarScalarFieldEnum)[keyof typeof CalendarScalarFieldEnum]


export const CalendarUnitScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  position: 'position',
  name: 'name',
  displayName: 'displayName',
  displayNameShort: 'displayNameShort',
  displayNamePlural: 'displayNamePlural',
  formatMode: 'formatMode',
  formatShorthand: 'formatShorthand',
  duration: 'duration',
  treeDepth: 'treeDepth',
  calendarId: 'calendarId'
} as const

export type CalendarUnitScalarFieldEnum = (typeof CalendarUnitScalarFieldEnum)[keyof typeof CalendarUnitScalarFieldEnum]


export const CalendarUnitRelationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  label: 'label',
  repeats: 'repeats',
  position: 'position',
  parentUnitId: 'parentUnitId',
  childUnitId: 'childUnitId'
} as const

export type CalendarUnitRelationScalarFieldEnum = (typeof CalendarUnitRelationScalarFieldEnum)[keyof typeof CalendarUnitRelationScalarFieldEnum]


export const SavedColorScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  value: 'value',
  label: 'label',
  worldId: 'worldId'
} as const

export type SavedColorScalarFieldEnum = (typeof SavedColorScalarFieldEnum)[keyof typeof SavedColorScalarFieldEnum]


export const FlagsScalarFieldEnum = {
  value: 'value'
} as const

export type FlagsScalarFieldEnum = (typeof FlagsScalarFieldEnum)[keyof typeof FlagsScalarFieldEnum]


export const UserFavoriteIconSetScalarFieldEnum = {
  id: 'id',
  iconSet: 'iconSet',
  userId: 'userId'
} as const

export type UserFavoriteIconSetScalarFieldEnum = (typeof UserFavoriteIconSetScalarFieldEnum)[keyof typeof UserFavoriteIconSetScalarFieldEnum]


export const WorldCommonIconSetScalarFieldEnum = {
  id: 'id',
  iconSet: 'iconSet',
  worldId: 'worldId'
} as const

export type WorldCommonIconSetScalarFieldEnum = (typeof WorldCommonIconSetScalarFieldEnum)[keyof typeof WorldCommonIconSetScalarFieldEnum]


export const MentionScalarFieldEnum = {
  sourceId: 'sourceId',
  targetId: 'targetId',
  sourceType: 'sourceType',
  targetType: 'targetType',
  sourceActorId: 'sourceActorId',
  sourceEventId: 'sourceEventId',
  sourceArticleId: 'sourceArticleId',
  sourceTagId: 'sourceTagId',
  targetActorId: 'targetActorId',
  targetEventId: 'targetEventId',
  targetArticleId: 'targetArticleId',
  targetTagId: 'targetTagId'
} as const

export type MentionScalarFieldEnum = (typeof MentionScalarFieldEnum)[keyof typeof MentionScalarFieldEnum]


export const MindmapNodeScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  positionX: 'positionX',
  positionY: 'positionY',
  parentActorId: 'parentActorId',
  worldId: 'worldId'
} as const

export type MindmapNodeScalarFieldEnum = (typeof MindmapNodeScalarFieldEnum)[keyof typeof MindmapNodeScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  deletionScheduledAt: 'deletionScheduledAt',
  email: 'email',
  username: 'username',
  password: 'password',
  bio: 'bio',
  level: 'level',
  avatarId: 'avatarId'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CollaboratingUserScalarFieldEnum = {
  access: 'access',
  userId: 'userId',
  worldId: 'worldId'
} as const

export type CollaboratingUserScalarFieldEnum = (typeof CollaboratingUserScalarFieldEnum)[keyof typeof CollaboratingUserScalarFieldEnum]


export const TagScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  worldId: 'worldId'
} as const

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum]


export const WikiArticleScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  icon: 'icon',
  color: 'color',
  contentRich: 'contentRich',
  contentYjs: 'contentYjs',
  position: 'position',
  worldId: 'worldId',
  parentId: 'parentId'
} as const

export type WikiArticleScalarFieldEnum = (typeof WikiArticleScalarFieldEnum)[keyof typeof WikiArticleScalarFieldEnum]


export const WorldScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  description: 'description',
  calendar: 'calendar',
  timeOrigin: 'timeOrigin',
  ownerId: 'ownerId',
  accessMode: 'accessMode'
} as const

export type WorldScalarFieldEnum = (typeof WorldScalarFieldEnum)[keyof typeof WorldScalarFieldEnum]


export const WorldEventScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  type: 'type',
  icon: 'icon',
  color: 'color',
  name: 'name',
  timestamp: 'timestamp',
  revokedAt: 'revokedAt',
  description: 'description',
  descriptionRich: 'descriptionRich',
  descriptionYjs: 'descriptionYjs',
  customName: 'customName',
  externalLink: 'externalLink',
  extraFields: 'extraFields',
  worldId: 'worldId',
  worldEventTrackId: 'worldEventTrackId'
} as const

export type WorldEventScalarFieldEnum = (typeof WorldEventScalarFieldEnum)[keyof typeof WorldEventScalarFieldEnum]


export const WorldEventDeltaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  timestamp: 'timestamp',
  name: 'name',
  description: 'description',
  descriptionRich: 'descriptionRich',
  worldEventId: 'worldEventId'
} as const

export type WorldEventDeltaScalarFieldEnum = (typeof WorldEventDeltaScalarFieldEnum)[keyof typeof WorldEventDeltaScalarFieldEnum]


export const WorldEventTrackScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  position: 'position',
  visible: 'visible',
  worldId: 'worldId'
} as const

export type WorldEventTrackScalarFieldEnum = (typeof WorldEventTrackScalarFieldEnum)[keyof typeof WorldEventTrackScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'AnnouncementType'
 */
export type EnumAnnouncementTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AnnouncementType'>
    


/**
 * Reference to a field of type 'AnnouncementType[]'
 */
export type ListEnumAnnouncementTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AnnouncementType[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'AssetType'
 */
export type EnumAssetTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AssetType'>
    


/**
 * Reference to a field of type 'AssetType[]'
 */
export type ListEnumAssetTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AssetType[]'>
    


/**
 * Reference to a field of type 'AssetStatus'
 */
export type EnumAssetStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AssetStatus'>
    


/**
 * Reference to a field of type 'AssetStatus[]'
 */
export type ListEnumAssetStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'AssetStatus[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    


/**
 * Reference to a field of type 'CalendarUnitFormatMode'
 */
export type EnumCalendarUnitFormatModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CalendarUnitFormatMode'>
    


/**
 * Reference to a field of type 'CalendarUnitFormatMode[]'
 */
export type ListEnumCalendarUnitFormatModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CalendarUnitFormatMode[]'>
    


/**
 * Reference to a field of type 'FlagValue'
 */
export type EnumFlagValueFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'FlagValue'>
    


/**
 * Reference to a field of type 'FlagValue[]'
 */
export type ListEnumFlagValueFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'FlagValue[]'>
    


/**
 * Reference to a field of type 'MentionedEntity'
 */
export type EnumMentionedEntityFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MentionedEntity'>
    


/**
 * Reference to a field of type 'MentionedEntity[]'
 */
export type ListEnumMentionedEntityFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'MentionedEntity[]'>
    


/**
 * Reference to a field of type 'UserLevel'
 */
export type EnumUserLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserLevel'>
    


/**
 * Reference to a field of type 'UserLevel[]'
 */
export type ListEnumUserLevelFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'UserLevel[]'>
    


/**
 * Reference to a field of type 'CollaboratorAccess'
 */
export type EnumCollaboratorAccessFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CollaboratorAccess'>
    


/**
 * Reference to a field of type 'CollaboratorAccess[]'
 */
export type ListEnumCollaboratorAccessFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'CollaboratorAccess[]'>
    


/**
 * Reference to a field of type 'WorldCalendarType'
 */
export type EnumWorldCalendarTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldCalendarType'>
    


/**
 * Reference to a field of type 'WorldCalendarType[]'
 */
export type ListEnumWorldCalendarTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldCalendarType[]'>
    


/**
 * Reference to a field of type 'WorldAccessMode'
 */
export type EnumWorldAccessModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldAccessMode'>
    


/**
 * Reference to a field of type 'WorldAccessMode[]'
 */
export type ListEnumWorldAccessModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldAccessMode[]'>
    


/**
 * Reference to a field of type 'WorldEventType'
 */
export type EnumWorldEventTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldEventType'>
    


/**
 * Reference to a field of type 'WorldEventType[]'
 */
export type ListEnumWorldEventTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldEventType[]'>
    


/**
 * Reference to a field of type 'WorldEventField[]'
 */
export type ListEnumWorldEventFieldFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldEventField[]'>
    


/**
 * Reference to a field of type 'WorldEventField'
 */
export type EnumWorldEventFieldFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'WorldEventField'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  actor?: Prisma.ActorOmit
  userAnnouncement?: Prisma.UserAnnouncementOmit
  asset?: Prisma.AssetOmit
  calendar?: Prisma.CalendarOmit
  calendarUnit?: Prisma.CalendarUnitOmit
  calendarUnitRelation?: Prisma.CalendarUnitRelationOmit
  savedColor?: Prisma.SavedColorOmit
  flags?: Prisma.FlagsOmit
  userFavoriteIconSet?: Prisma.UserFavoriteIconSetOmit
  worldCommonIconSet?: Prisma.WorldCommonIconSetOmit
  mention?: Prisma.MentionOmit
  mindmapNode?: Prisma.MindmapNodeOmit
  user?: Prisma.UserOmit
  collaboratingUser?: Prisma.CollaboratingUserOmit
  tag?: Prisma.TagOmit
  wikiArticle?: Prisma.WikiArticleOmit
  world?: Prisma.WorldOmit
  worldEvent?: Prisma.WorldEventOmit
  worldEventDelta?: Prisma.WorldEventDeltaOmit
  worldEventTrack?: Prisma.WorldEventTrackOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

