/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ToolsToolsRouteImport } from './routes/tools/_tools'
import { Route as SecretMusicRouteImport } from './routes/secret/music'
import { Route as ProfileProfileRouteImport } from './routes/profile/_profile'
import { Route as WorldWorldIdWorldRouteImport } from './routes/world.$worldId/_world'
import { Route as ToolsToolsImageConverterRouteImport } from './routes/tools/_tools.image-converter'
import { Route as ProfileProfileStorageRouteImport } from './routes/profile/_profile.storage'
import { Route as ProfileProfilePublicRouteImport } from './routes/profile/_profile.public'
import { Route as WorldWorldIdWorldTimelineRouteImport } from './routes/world.$worldId/_world.timeline'
import { Route as WorldWorldIdWorldSettingsRouteImport } from './routes/world.$worldId/_world.settings'
import { Route as WorldWorldIdWorldMindmapRouteImport } from './routes/world.$worldId/_world.mindmap'
import { Route as WorldWorldIdWorldWikiWikiRouteImport } from './routes/world.$worldId/_world.wiki/_wiki'
import { Route as WorldWorldIdWorldWikiWikiIndexRouteImport } from './routes/world.$worldId/_world.wiki/_wiki.index'
import { Route as WorldWorldIdWorldWikiWikiArticleIdRouteImport } from './routes/world.$worldId/_world.wiki/_wiki.$articleId'

const ToolsRouteImport = createFileRoute('/tools')()
const ProfileRouteImport = createFileRoute('/profile')()
const WorldWorldIdRouteImport = createFileRoute('/world/$worldId')()
const WorldWorldIdWorldWikiRouteImport = createFileRoute(
  '/world/$worldId/_world/wiki',
)()

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWorldIdRoute = WorldWorldIdRouteImport.update({
  id: '/world/$worldId',
  path: '/world/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ToolsToolsRoute = ToolsToolsRouteImport.update({
  id: '/_tools',
  getParentRoute: () => ToolsRoute,
} as any)
const SecretMusicRoute = SecretMusicRouteImport.update({
  id: '/secret/music',
  path: '/secret/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileRoute = ProfileProfileRouteImport.update({
  id: '/_profile',
  getParentRoute: () => ProfileRoute,
} as any)
const WorldWorldIdWorldRoute = WorldWorldIdWorldRouteImport.update({
  id: '/_world',
  getParentRoute: () => WorldWorldIdRoute,
} as any)
const ToolsToolsImageConverterRoute =
  ToolsToolsImageConverterRouteImport.update({
    id: '/image-converter',
    path: '/image-converter',
    getParentRoute: () => ToolsToolsRoute,
  } as any)
const ProfileProfileStorageRoute = ProfileProfileStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ProfileProfileRoute,
} as any)
const ProfileProfilePublicRoute = ProfileProfilePublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => ProfileProfileRoute,
} as any)
const WorldWorldIdWorldWikiRoute = WorldWorldIdWorldWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => WorldWorldIdWorldRoute,
} as any)
const WorldWorldIdWorldTimelineRoute =
  WorldWorldIdWorldTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => WorldWorldIdWorldRoute,
  } as any)
const WorldWorldIdWorldSettingsRoute =
  WorldWorldIdWorldSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorldWorldIdWorldRoute,
  } as any)
const WorldWorldIdWorldMindmapRoute =
  WorldWorldIdWorldMindmapRouteImport.update({
    id: '/mindmap',
    path: '/mindmap',
    getParentRoute: () => WorldWorldIdWorldRoute,
  } as any)
const WorldWorldIdWorldWikiWikiRoute =
  WorldWorldIdWorldWikiWikiRouteImport.update({
    id: '/_wiki',
    getParentRoute: () => WorldWorldIdWorldWikiRoute,
  } as any)
const WorldWorldIdWorldWikiWikiIndexRoute =
  WorldWorldIdWorldWikiWikiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorldWorldIdWorldWikiWikiRoute,
  } as any)
const WorldWorldIdWorldWikiWikiArticleIdRoute =
  WorldWorldIdWorldWikiWikiArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => WorldWorldIdWorldWikiWikiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof ProfileProfileRouteWithChildren
  '/secret/music': typeof SecretMusicRoute
  '/tools': typeof ToolsToolsRouteWithChildren
  '/profile/': typeof ProfileIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/profile/public': typeof ProfileProfilePublicRoute
  '/profile/storage': typeof ProfileProfileStorageRoute
  '/tools/image-converter': typeof ToolsToolsImageConverterRoute
  '/world/$worldId': typeof WorldWorldIdWorldRouteWithChildren
  '/world/$worldId/mindmap': typeof WorldWorldIdWorldMindmapRoute
  '/world/$worldId/settings': typeof WorldWorldIdWorldSettingsRoute
  '/world/$worldId/timeline': typeof WorldWorldIdWorldTimelineRoute
  '/world/$worldId/wiki': typeof WorldWorldIdWorldWikiWikiRouteWithChildren
  '/world/$worldId/wiki/$articleId': typeof WorldWorldIdWorldWikiWikiArticleIdRoute
  '/world/$worldId/wiki/': typeof WorldWorldIdWorldWikiWikiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof ProfileIndexRoute
  '/secret/music': typeof SecretMusicRoute
  '/tools': typeof ToolsIndexRoute
  '/profile/public': typeof ProfileProfilePublicRoute
  '/profile/storage': typeof ProfileProfileStorageRoute
  '/tools/image-converter': typeof ToolsToolsImageConverterRoute
  '/world/$worldId': typeof WorldWorldIdWorldRouteWithChildren
  '/world/$worldId/mindmap': typeof WorldWorldIdWorldMindmapRoute
  '/world/$worldId/settings': typeof WorldWorldIdWorldSettingsRoute
  '/world/$worldId/timeline': typeof WorldWorldIdWorldTimelineRoute
  '/world/$worldId/wiki': typeof WorldWorldIdWorldWikiWikiIndexRoute
  '/world/$worldId/wiki/$articleId': typeof WorldWorldIdWorldWikiWikiArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof ProfileRouteWithChildren
  '/profile/_profile': typeof ProfileProfileRouteWithChildren
  '/secret/music': typeof SecretMusicRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/_tools': typeof ToolsToolsRouteWithChildren
  '/profile/': typeof ProfileIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/profile/_profile/public': typeof ProfileProfilePublicRoute
  '/profile/_profile/storage': typeof ProfileProfileStorageRoute
  '/tools/_tools/image-converter': typeof ToolsToolsImageConverterRoute
  '/world/$worldId': typeof WorldWorldIdRouteWithChildren
  '/world/$worldId/_world': typeof WorldWorldIdWorldRouteWithChildren
  '/world/$worldId/_world/mindmap': typeof WorldWorldIdWorldMindmapRoute
  '/world/$worldId/_world/settings': typeof WorldWorldIdWorldSettingsRoute
  '/world/$worldId/_world/timeline': typeof WorldWorldIdWorldTimelineRoute
  '/world/$worldId/_world/wiki': typeof WorldWorldIdWorldWikiRouteWithChildren
  '/world/$worldId/_world/wiki/_wiki': typeof WorldWorldIdWorldWikiWikiRouteWithChildren
  '/world/$worldId/_world/wiki/_wiki/$articleId': typeof WorldWorldIdWorldWikiWikiArticleIdRoute
  '/world/$worldId/_world/wiki/_wiki/': typeof WorldWorldIdWorldWikiWikiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/register'
    | '/profile'
    | '/secret/music'
    | '/tools'
    | '/profile/'
    | '/tools/'
    | '/profile/public'
    | '/profile/storage'
    | '/tools/image-converter'
    | '/world/$worldId'
    | '/world/$worldId/mindmap'
    | '/world/$worldId/settings'
    | '/world/$worldId/timeline'
    | '/world/$worldId/wiki'
    | '/world/$worldId/wiki/$articleId'
    | '/world/$worldId/wiki/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/register'
    | '/profile'
    | '/secret/music'
    | '/tools'
    | '/profile/public'
    | '/profile/storage'
    | '/tools/image-converter'
    | '/world/$worldId'
    | '/world/$worldId/mindmap'
    | '/world/$worldId/settings'
    | '/world/$worldId/timeline'
    | '/world/$worldId/wiki'
    | '/world/$worldId/wiki/$articleId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/register'
    | '/profile'
    | '/profile/_profile'
    | '/secret/music'
    | '/tools'
    | '/tools/_tools'
    | '/profile/'
    | '/tools/'
    | '/profile/_profile/public'
    | '/profile/_profile/storage'
    | '/tools/_tools/image-converter'
    | '/world/$worldId'
    | '/world/$worldId/_world'
    | '/world/$worldId/_world/mindmap'
    | '/world/$worldId/_world/settings'
    | '/world/$worldId/_world/timeline'
    | '/world/$worldId/_world/wiki'
    | '/world/$worldId/_world/wiki/_wiki'
    | '/world/$worldId/_world/wiki/_wiki/$articleId'
    | '/world/$worldId/_world/wiki/_wiki/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SecretMusicRoute: typeof SecretMusicRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  WorldWorldIdRoute: typeof WorldWorldIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$worldId': {
      id: '/world/$worldId'
      path: '/world/$worldId'
      fullPath: '/world/$worldId'
      preLoaderRoute: typeof WorldWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/tools/_tools': {
      id: '/tools/_tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsToolsRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/secret/music': {
      id: '/secret/music'
      path: '/secret/music'
      fullPath: '/secret/music'
      preLoaderRoute: typeof SecretMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/_profile': {
      id: '/profile/_profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileProfileRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/world/$worldId/_world': {
      id: '/world/$worldId/_world'
      path: '/world/$worldId'
      fullPath: '/world/$worldId'
      preLoaderRoute: typeof WorldWorldIdWorldRouteImport
      parentRoute: typeof WorldWorldIdRoute
    }
    '/tools/_tools/image-converter': {
      id: '/tools/_tools/image-converter'
      path: '/image-converter'
      fullPath: '/tools/image-converter'
      preLoaderRoute: typeof ToolsToolsImageConverterRouteImport
      parentRoute: typeof ToolsToolsRoute
    }
    '/profile/_profile/storage': {
      id: '/profile/_profile/storage'
      path: '/storage'
      fullPath: '/profile/storage'
      preLoaderRoute: typeof ProfileProfileStorageRouteImport
      parentRoute: typeof ProfileProfileRoute
    }
    '/profile/_profile/public': {
      id: '/profile/_profile/public'
      path: '/public'
      fullPath: '/profile/public'
      preLoaderRoute: typeof ProfileProfilePublicRouteImport
      parentRoute: typeof ProfileProfileRoute
    }
    '/world/$worldId/_world/wiki': {
      id: '/world/$worldId/_world/wiki'
      path: '/wiki'
      fullPath: '/world/$worldId/wiki'
      preLoaderRoute: typeof WorldWorldIdWorldWikiRouteImport
      parentRoute: typeof WorldWorldIdWorldRoute
    }
    '/world/$worldId/_world/timeline': {
      id: '/world/$worldId/_world/timeline'
      path: '/timeline'
      fullPath: '/world/$worldId/timeline'
      preLoaderRoute: typeof WorldWorldIdWorldTimelineRouteImport
      parentRoute: typeof WorldWorldIdWorldRoute
    }
    '/world/$worldId/_world/settings': {
      id: '/world/$worldId/_world/settings'
      path: '/settings'
      fullPath: '/world/$worldId/settings'
      preLoaderRoute: typeof WorldWorldIdWorldSettingsRouteImport
      parentRoute: typeof WorldWorldIdWorldRoute
    }
    '/world/$worldId/_world/mindmap': {
      id: '/world/$worldId/_world/mindmap'
      path: '/mindmap'
      fullPath: '/world/$worldId/mindmap'
      preLoaderRoute: typeof WorldWorldIdWorldMindmapRouteImport
      parentRoute: typeof WorldWorldIdWorldRoute
    }
    '/world/$worldId/_world/wiki/_wiki': {
      id: '/world/$worldId/_world/wiki/_wiki'
      path: '/wiki'
      fullPath: '/world/$worldId/wiki'
      preLoaderRoute: typeof WorldWorldIdWorldWikiWikiRouteImport
      parentRoute: typeof WorldWorldIdWorldWikiRoute
    }
    '/world/$worldId/_world/wiki/_wiki/': {
      id: '/world/$worldId/_world/wiki/_wiki/'
      path: '/'
      fullPath: '/world/$worldId/wiki/'
      preLoaderRoute: typeof WorldWorldIdWorldWikiWikiIndexRouteImport
      parentRoute: typeof WorldWorldIdWorldWikiWikiRoute
    }
    '/world/$worldId/_world/wiki/_wiki/$articleId': {
      id: '/world/$worldId/_world/wiki/_wiki/$articleId'
      path: '/$articleId'
      fullPath: '/world/$worldId/wiki/$articleId'
      preLoaderRoute: typeof WorldWorldIdWorldWikiWikiArticleIdRouteImport
      parentRoute: typeof WorldWorldIdWorldWikiWikiRoute
    }
  }
}

interface ProfileProfileRouteChildren {
  ProfileProfilePublicRoute: typeof ProfileProfilePublicRoute
  ProfileProfileStorageRoute: typeof ProfileProfileStorageRoute
}

const ProfileProfileRouteChildren: ProfileProfileRouteChildren = {
  ProfileProfilePublicRoute: ProfileProfilePublicRoute,
  ProfileProfileStorageRoute: ProfileProfileStorageRoute,
}

const ProfileProfileRouteWithChildren = ProfileProfileRoute._addFileChildren(
  ProfileProfileRouteChildren,
)

interface ProfileRouteChildren {
  ProfileProfileRoute: typeof ProfileProfileRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileProfileRoute: ProfileProfileRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ToolsToolsRouteChildren {
  ToolsToolsImageConverterRoute: typeof ToolsToolsImageConverterRoute
}

const ToolsToolsRouteChildren: ToolsToolsRouteChildren = {
  ToolsToolsImageConverterRoute: ToolsToolsImageConverterRoute,
}

const ToolsToolsRouteWithChildren = ToolsToolsRoute._addFileChildren(
  ToolsToolsRouteChildren,
)

interface ToolsRouteChildren {
  ToolsToolsRoute: typeof ToolsToolsRouteWithChildren
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsToolsRoute: ToolsToolsRouteWithChildren,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface WorldWorldIdWorldWikiWikiRouteChildren {
  WorldWorldIdWorldWikiWikiArticleIdRoute: typeof WorldWorldIdWorldWikiWikiArticleIdRoute
  WorldWorldIdWorldWikiWikiIndexRoute: typeof WorldWorldIdWorldWikiWikiIndexRoute
}

const WorldWorldIdWorldWikiWikiRouteChildren: WorldWorldIdWorldWikiWikiRouteChildren =
  {
    WorldWorldIdWorldWikiWikiArticleIdRoute:
      WorldWorldIdWorldWikiWikiArticleIdRoute,
    WorldWorldIdWorldWikiWikiIndexRoute: WorldWorldIdWorldWikiWikiIndexRoute,
  }

const WorldWorldIdWorldWikiWikiRouteWithChildren =
  WorldWorldIdWorldWikiWikiRoute._addFileChildren(
    WorldWorldIdWorldWikiWikiRouteChildren,
  )

interface WorldWorldIdWorldWikiRouteChildren {
  WorldWorldIdWorldWikiWikiRoute: typeof WorldWorldIdWorldWikiWikiRouteWithChildren
}

const WorldWorldIdWorldWikiRouteChildren: WorldWorldIdWorldWikiRouteChildren = {
  WorldWorldIdWorldWikiWikiRoute: WorldWorldIdWorldWikiWikiRouteWithChildren,
}

const WorldWorldIdWorldWikiRouteWithChildren =
  WorldWorldIdWorldWikiRoute._addFileChildren(
    WorldWorldIdWorldWikiRouteChildren,
  )

interface WorldWorldIdWorldRouteChildren {
  WorldWorldIdWorldMindmapRoute: typeof WorldWorldIdWorldMindmapRoute
  WorldWorldIdWorldSettingsRoute: typeof WorldWorldIdWorldSettingsRoute
  WorldWorldIdWorldTimelineRoute: typeof WorldWorldIdWorldTimelineRoute
  WorldWorldIdWorldWikiRoute: typeof WorldWorldIdWorldWikiRouteWithChildren
}

const WorldWorldIdWorldRouteChildren: WorldWorldIdWorldRouteChildren = {
  WorldWorldIdWorldMindmapRoute: WorldWorldIdWorldMindmapRoute,
  WorldWorldIdWorldSettingsRoute: WorldWorldIdWorldSettingsRoute,
  WorldWorldIdWorldTimelineRoute: WorldWorldIdWorldTimelineRoute,
  WorldWorldIdWorldWikiRoute: WorldWorldIdWorldWikiRouteWithChildren,
}

const WorldWorldIdWorldRouteWithChildren =
  WorldWorldIdWorldRoute._addFileChildren(WorldWorldIdWorldRouteChildren)

interface WorldWorldIdRouteChildren {
  WorldWorldIdWorldRoute: typeof WorldWorldIdWorldRouteWithChildren
}

const WorldWorldIdRouteChildren: WorldWorldIdRouteChildren = {
  WorldWorldIdWorldRoute: WorldWorldIdWorldRouteWithChildren,
}

const WorldWorldIdRouteWithChildren = WorldWorldIdRoute._addFileChildren(
  WorldWorldIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SecretMusicRoute: SecretMusicRoute,
  ToolsRoute: ToolsRouteWithChildren,
  WorldWorldIdRoute: WorldWorldIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
