# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-styx:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run Styx tests
      run: yarn test:styx
    
  test-rhea:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Run Rhea tests
      run: yarn test:rhea

  build-container:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Build Container
      run: yarn docker:prod:push
